### ISSUE TITLE
Document360 Connector  

### ISSUE THREAD

**Issue by robertoamoreno** [danswer-ai/danswer#1111]
expects primary_owners to be a list of dictionaries, but it's being provided with a list of strings instead. 

Traceback (most recent call last):
  File "/app/danswer/background/indexing/run_indexing.py", line 174, in _run_indexing
    for doc_batch in doc_batch_generator:
  File "/app/danswer/connectors/document360/connector.py", line 146, in _process_articles
    document = Document(
               ^^^^^^^^^
  File "pydantic/main.py", line 341, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for Document
primary_owners -> 0
  value is not a valid dict (type=type_error.dict)

**Comment by robertoamoreno** [comment]
Fix 
```
authors = [
    {"name": author.get("name", "Unknown"), "email": author["email_id"]}
    for author in article_details.get("authors", [])
    if author["email_id"]
]
```
