### ISSUE TITLE
Quick-start tutorial runs with inference_model_server error

### ISSUE THREAD

**Issue by slovx2** [danswer-ai/danswer#1352]
After following the Quick Start document to deploy using docker-compose, I found that I could not access http://localhost:3000. Then I checked the logs for the api_server by running:
```
docker logs danswer-stack-api_server-1
```

The logs are as follows:
```
04/19/2024 11:49:00 AM              main.py 238 : Waiting on Vespa, retrying in 5 seconds...
04/19/2024 11:49:05 AM              main.py 238 : Waiting on Vespa, retrying in 5 seconds...
04/19/2024 11:49:10 AM              main.py 238 : Waiting on Vespa, retrying in 5 seconds...
04/19/2024 11:49:16 AM              main.py 238 : Waiting on Vespa, retrying in 5 seconds...
04/19/2024 11:49:21 AM              main.py 238 : Waiting on Vespa, retrying in 5 seconds...
04/19/2024 11:49:26 AM              main.py 241 : Model Server: http://inference_model_server:9000
04/19/2024 11:49:27 AM search_nlp_models.py 199 : Failed to run test embedding, retrying in 5 seconds...
04/19/2024 11:49:32 AM search_nlp_models.py 199 : Failed to run test embedding, retrying in 5 seconds...
04/19/2024 11:49:37 AM search_nlp_models.py 199 : Failed to run test embedding, retrying in 5 seconds...
04/19/2024 11:49:42 AM search_nlp_models.py 199 : Failed to run test embedding, retrying in 5 seconds...
04/19/2024 11:49:48 AM search_nlp_models.py 199 : Failed to run test embedding, retrying in 5 seconds...
04/19/2024 11:49:53 AM search_nlp_models.py 199 : Failed to run test embedding, retrying in 5 seconds...
04/19/2024 11:49:58 AM search_nlp_models.py 199 : Failed to run test embedding, retrying in 5 seconds...
04/19/2024 11:50:03 AM search_nlp_models.py 199 : Failed to run test embedding, retrying in 5 seconds...

```

Next, I checked the Vespa logs by running:
```
docker logs -f danswer-stack-index-1
```

The logs are as follows

```
[2024-04-19 11:48:17.484] INFO    config-sentinel  sentinel.config.frt.frtconfigagent   No response / error from config server. This is normal before an application package is deployed. (key: name=cloud.config.sentinel,configId=hosts/a2e8d68b04ac) (errcode=103, validresponse:0), trying again in 8.000000 seconds
[2024-04-19 11:48:41.638] INFO    configproxy      configproxy.com.yahoo.vespa.config.proxy.RpcConfigSourceClient       Subscribe for 'name=cloud.config.sentinel,configId=hosts/a2e8d68b04ac,aa9115ebf63cfc6721f75ada21d7cdfa' failed, closing subscriber: Subscribe for 'name=cloud.config.sentinel,configId=hosts/a2e8d68b04ac' timed out (timeout was 44000 ms): name=cloud.config.sentinel,configId=hosts/a2e8d68b04ac, Current generation: 0, Generation changed: false, Config changed: false
[2024-04-19 11:48:41.641] INFO    configproxy      configproxy.com.yahoo.config.subscription.impl.JRTConfigRequester    Request failed: Failed request (No application exists) from Connection { Socket[addr=/10.89.1.13,port=60404,localport=19070] }\nConnection spec: tcp/a2e8d68b04ac:19070
[2024-04-19 11:48:51.403] INFO    configproxy      configproxy.com.yahoo.vespa.config.proxy.DelayedResponseHandler      Timed out (timeout 25000) getting config name=cloud.config.sentinel,configId=hosts/a2e8d68b04ac, will retry
[2024-04-19 11:48:55.531] INFO    config-sentinel  sentinel.config.frt.frtconfigagent   No response / error from config server. This is normal before an application package is deployed. (key: name=cloud.config.sentinel,configId=hosts/a2e8d68b04ac) (errcode=103, validresponse:0), trying again in 9.000000 seconds
[2024-04-19 11:49:25.647] INFO    configproxy      configproxy.com.yahoo.vespa.config.proxy.RpcConfigSourceClient       Subscribe for 'name=cloud.config.sentinel,configId=hosts/a2e8d68b04ac,aa9115ebf63cfc6721f75ada21d7cdfa' failed, closing subscriber: Subscribe for 'name=cloud.config.sentinel,configId=hosts/a2e8d68b04ac' timed out (timeout was 44000 ms): name=cloud.config.sentinel,configId=hosts/a2e8d68b04ac, Current generation: 0, Generation changed: false, Config changed: false
[2024-04-19 11:49:25.649] INFO    configproxy      configproxy.com.yahoo.config.subscription.impl.JRTConfigRequester    Request failed: Failed request (No application exists) from Connection { Socket[addr=/10.89.1.13,port=60404,localport=19070] }\nConnection spec: tcp/a2e8d68b04ac:19070
[2024-04-19 11:49:30.403] INFO    configproxy      configproxy.com.yahoo.vespa.config.proxy.DelayedResponseHandler      Timed out (timeout 25000) getting config name=cloud.config.sentinel,configId=hosts/a2e8d68b04ac, will retry
[2024-04-19 11:49:34.569] INFO    config-sentinel  sentinel.config.frt.frtconfigagent   No response / error from config server. This is normal before an application package is deployed. (key: name=cloud.config.sentinel,configId=hosts/a2e8d68b04ac) (errcode=103, validresponse:0), trying again in 10.000000 seconds
[2024-04-19 11:49:44.389] WARNING config-sentinel  sentinel.config-sentinel     Timeout getting config, please check your setup. Will exit and restart: Timed out while subscribing to 'cloud.config.sentinel', configid 'hosts/a2e8d68b04ac'
[2024-04-19 11:49:44.392] INFO    config-sentinel  runserver    will restart in 0 seconds
```

Is there an issue with the Vespa configuration in docker-compose file, or is it a problem with my network environment?

**Comment by slovx2** [comment]
Update
Found the real cause: the inference_model_server is reporting a 503 error 

```
ERROR:    Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 734, in lifespan
    async with self.lifespan_context(app) as maybe_state:
  File "/usr/local/lib/python3.11/contextlib.py", line 210, in __aenter__
    return await anext(self.gen)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/app/danswer/main.py", line 242, in lifespan
    warm_up_encoders(
  File "/app/danswer/search/search_nlp_models.py", line 196, in warm_up_encoders
    embed_model.encode(texts=[warm_up_str], text_type=EmbedTextType.QUERY)
  File "/app/danswer/search/search_nlp_models.py", line 120, in encode
    response.raise_for_status()
  File "/usr/local/lib/python3.11/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 503 Server Error: Service Unavailable for url: http://inference_model_server:9000/encoder/bi-encoder-embed
```

**Comment by mcandio** [comment]
Is this inference model needed when using the helm chart? or the helm chart is not fully operational yet? I am receiving the same error, of course I have nothing deployed on port 9000 on AKS, the embeddings test embedding will fail

**Comment by slovx2** [comment]
Update

I found the reason why the inference_model_server was giving an error. Due to my network issues, downloading models from Hugging Face was quite slow, and the inference_model_server did not provide any progress indicators for the download.

After adding a proxy, the inference_model_server successfully downloaded the model. However, when the api_server tried to access the inference_model_server, it reported a 500 Internal Server Error.

```
INFO:     172.22.0.7:45994 - "POST /encoder/bi-encoder-embed HTTP/1.1" 500 Internal Server Error
04/20/2024 03:59:01 AM          encoders.py  40 : Loading thenlper/gte-small
No sentence-transformers model found with name thenlper/gte-small. Creating a new one with MEAN pooling.
INFO:     172.22.0.7:46026 - "POST /encoder/bi-encoder-embed HTTP/1.1" 500 Internal Server Error
04/20/2024 03:59:08 AM          encoders.py  40 : Loading thenlper/gte-small
No sentence-transformers model found with name thenlper/gte-small. Creating a new one with MEAN pooling.
INFO:     172.22.0.7:46064 - "POST /encoder/bi-encoder-embed HTTP/1.1" 500 Internal Server Error
04/20/2024 03:59:17 AM          encoders.py  40 : Loading thenlper/gte-small
No sentence-transformers model found with name thenlper/gte-small. Creating a new one with MEAN pooling.
INFO:     172.22.0.7:46104 - "POST /encoder/bi-encoder-embed HTTP/1.1" 500 Internal Server Error
04/20/2024 03:59:29 AM          encoders.py  40 : Loading thenlper/gte-small
INFO:     172.22.0.7:46142 - "POST /encoder/bi-encoder-embed HTTP/1.1" 500 Internal Server Error
04/20/2024 04:01:24 AM          encoders.py  40 : Loading thenlper/gte-small
```

**Comment by robinwo** [comment]
Same issue here...

`04/25/2024 05:38:27 PM              main.py 200 : Using Embedding model: "intfloat/e5-base-v2"
04/25/2024 05:38:27 PM              main.py 202 : Query embedding prefix: "query: "
04/25/2024 05:38:27 PM              main.py 203 : Passage embedding prefix: "passage: "
04/25/2024 05:38:27 PM              main.py 210 : Verifying query preprocessing (NLTK) data is downloaded
04/25/2024 05:38:27 PM     search_runner.py  45 : stopwords is already downloaded.
04/25/2024 05:38:27 PM     search_runner.py  48 : Downloading wordnet...
04/25/2024 05:38:27 PM     search_runner.py  50 : wordnet downloaded successfully.
04/25/2024 05:38:27 PM     search_runner.py  45 : punkt is already downloaded.
04/25/2024 05:38:27 PM              main.py 213 : Verifying default connector/credential exist.
04/25/2024 05:38:27 PM              main.py 218 : Loading default Prompts and Personas
04/25/2024 05:38:27 PM              main.py 222 : Verifying Document Index(s) is/are available.
04/25/2024 05:38:27 PM              main.py 241 : Waiting on Vespa, retrying in 5 seconds...
04/25/2024 05:38:33 PM              main.py 244 : Model Server: http://inference_model_server:9000
04/25/2024 05:38:33 PM search_nlp_models.py 199 : Failed to run test embedding, retrying in 5 seconds...
04/25/2024 05:38:38 PM search_nlp_models.py 199 : Failed to run test embedding, retrying in 5 seconds...
04/25/2024 05:38:43 PM search_nlp_models.py 199 : Failed to run test embedding, retrying in 5 seconds...
04/25/2024 05:38:48 PM search_nlp_models.py 199 : Failed to run test embedding, retrying in 5 seconds...
04/25/2024 05:38:53 PM search_nlp_models.py 199 : Failed to run test embedding, retrying in 5 seconds...
04/25/2024 05:38:58 PM search_nlp_models.py 199 : Failed to run test embedding, retrying in 5 seconds...
04/25/2024 05:39:03 PM search_nlp_models.py 199 : Failed to run test embedding, retrying in 5 seconds...
04/25/2024 05:39:08 PM search_nlp_models.py 199 : Failed to run test embedding, retrying in 5 seconds...
04/25/2024 05:39:13 PM search_nlp_models.py 199 : Failed to run test embedding, retrying in 5 seconds...
04/25/2024 05:39:18 PM search_nlp_models.py 199 : Failed to run test embedding, retrying in 5 seconds...
04/25/2024 05:39:23 PM search_nlp_models.py 199 : Failed to run test embedding, retrying in 5 seconds...
04/25/2024 05:39:28 PM search_nlp_models.py 199 : Failed to run test embedding, retrying in 5 seconds...
04/25/2024 05:39:33 PM search_nlp_models.py 199 : Failed to run test embedding, retrying in 5 seconds...
04/25/2024 05:39:38 PM search_nlp_models.py 199 : Failed to run test embedding, retrying in 5 seconds...
04/25/2024 05:39:43 PM search_nlp_models.py 199 : Failed to run test embedding, retrying in 5 seconds...
04/25/2024 05:39:48 PM search_nlp_models.py 199 : Failed to run test embedding, retrying in 5 seconds...
04/25/2024 05:39:53 PM search_nlp_models.py 199 : Failed to run test embedding, retrying in 5 seconds...
04/25/2024 05:39:58 PM search_nlp_models.py 199 : Failed to run test embedding, retrying in 5 seconds...`
