### ISSUE TITLE
Google Drive PDF Parsing Issue

### ISSUE THREAD

**Issue by chrisedington** [danswer-ai/danswer#180]
I started to watch the `/var/log/update.log` on `danswer/danswer-background` and noticed the following exceptions raised:

```
07/15/2023 04:23:59 PM            update.py  95 : Starting new indexing attempt for connector: 'GoogleDriveConnector', with config: '{}', and with credentials: '[6]'
07/15/2023 04:24:00 PM    connector_auth.py  49 : Refreshed Google Drive tokens.
07/15/2023 04:24:01 PM         connector.py  75 : Parseable Documents in batch: ['2023 Consolidated SS + Flick - Financial Model', 'XX Cash Flow 2023', '351618_UASD3PGZ (3).pdf', '351618_UASD3PGZ (2).pdf', '351618_UASD3PGZ (1).pdf', '351618_UASD3PGZ.pdf', 'XX_SPL001_waybill_UASD3PGZ_A5 (7).pdf', 'XX_SPL001_waybill_UASD3PGZ_A5 (6).pdf', 'XX_SPL001_waybill_UASD3PGZ_A5 (5).pdf', 'XX_SPL001_waybill_UASD3PGZ_A5 (4).pdf', 'XX_SPL001_waybill_UASD3PGZ_A5 (3).pdf']
07/15/2023 04:24:17 PM             store.py 159 : Indexed 13 chunks into Typesense collection 'danswer_index', number failed: 0
07/15/2023 04:24:22 PM            timing.py  29 : encode_chunks took 5.2996666431427 seconds
07/15/2023 04:24:22 PM          indexing.py 167 : Indexed 13 chunks into Qdrant collection 'danswer_index', status: UpdateStatus.COMPLETED
07/15/2023 04:24:22 PM indexing_pipeline.py  44 : Indexed 0 new documents
07/15/2023 04:24:23 PM         connector.py  75 : Parseable Documents in batch: ['XX_SPL001_waybill_UASD3PGZ_A5 (2).pdf', 'XX_SPL001_waybill_UASD3PGZ_A5 (1).pdf', 'XX_SPL001_waybill_UASD3PGZ_A5.pdf', 'Order_351619_waybill (16).pdf', 'Order_351619_waybill (15).pdf', 'Order_351619_waybill (14).pdf', 'Order_351619_waybill (13).pdf', 'Order_351619_waybill (12).pdf', 'Order_351619_waybill (11).pdf', 'Order_351619_waybill (10).pdf', 'Order_351619_waybill (9).pdf', 'Order_351619_waybill (8).pdf']
07/15/2023 04:24:28 PM            update.py 176 : Indexing job with id 96 failed due to EOF marker not found
Traceback (most recent call last):
  File "/app/danswer/background/update.py", line 155, in run_indexing_jobs
    for doc_batch in doc_batch_generator:
  File "/app/danswer/connectors/google_drive/connector.py", line 165, in poll_source
    yield from self._fetch_docs_from_drive(start, end)
  File "/app/danswer/connectors/google_drive/connector.py", line 144, in _fetch_docs_from_drive
    text_contents = extract_text(file, service)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/danswer/connectors/google_drive/connector.py", line 101, in extract_text
    pdf_reader = PdfReader(pdf_stream)
                 ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/PyPDF2/_reader.py", line 319, in __init__
    self.read(stream)
  File "/usr/local/lib/python3.11/site-packages/PyPDF2/_reader.py", line 1415, in read
    self._find_eof_marker(stream)
  File "/usr/local/lib/python3.11/site-packages/PyPDF2/_reader.py", line 1471, in _find_eof_marker
    raise PdfReadError("EOF marker not found")
PyPDF2.errors.PdfReadError: EOF marker not found
```

**Comment by chrisedington** [comment]
I'm getting this in the UI, and the same Google Drive errors above (EOF)


<img width="1444" alt="Screenshot 2023-07-18 at 14 29 37" src="https://github.com/danswer-ai/danswer/assets/2725500/14f689e9-ee8b-446a-83b9-27fa144ce635">


<img width="1728" alt="Screenshot 2023-07-18 at 14 27 50" src="https://github.com/danswer-ai/danswer/assets/2725500/812d2e97-a17e-44b8-b80e-1f314475cecb">

**Comment by chrisedington** [comment]
Seems I found the issue that causes the exceptions in the original issue post.

```
07/15/2023 04:24:28 PM            update.py 176 : Indexing job with id 96 failed due to EOF marker not found
Traceback (most recent call last):
  File "/app/danswer/background/update.py", line 155, in run_indexing_jobs
    for doc_batch in doc_batch_generator:
  File "/app/danswer/connectors/google_drive/connector.py", line 165, in poll_source
    yield from self._fetch_docs_from_drive(start, end)
  File "/app/danswer/connectors/google_drive/connector.py", line 144, in _fetch_docs_from_drive
    text_contents = extract_text(file, service)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/danswer/connectors/google_drive/connector.py", line 101, in extract_text
    pdf_reader = PdfReader(pdf_stream)
                 ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/PyPDF2/_reader.py", line 319, in __init__
    self.read(stream)
  File "/usr/local/lib/python3.11/site-packages/PyPDF2/_reader.py", line 1415, in read
    self._find_eof_marker(stream)
  File "/usr/local/lib/python3.11/site-packages/PyPDF2/_reader.py", line 1471, in _find_eof_marker
    raise PdfReadError("EOF marker not found")
PyPDF2.errors.PdfReadError: EOF marker not found
```

This hack-fix seems to let it run, my Python isn't good enough to make a better suggestion unfortunately, but it at least lets the index run without a exception raised.

```
        try:
            pdf_reader = PdfReader(pdf_stream)
        except:
            pdf_reader = ""
```

**Comment by yuhongsun96** [comment]
Will fix this but probably not in that way, any chance you can attach/link a PDF for easy repro?

**Comment by chrisedington** [comment]
@yuhongsun96 sure, will see if I can narrow down which one it is

**Comment by yuhongsun96** [comment]
Made a bunch of pdf related changes, including fixing this. This particular one is handled in https://github.com/danswer-ai/danswer/pull/599
