### ISSUE TITLE
No module named 'danswer.search'

### ISSUE THREAD

**Issue by lucashaha** [danswer-ai/danswer#1837]
I use docker compose -f docker-compose.dev.yml -p danswer-stack up -d --pull always --force-recreate command to start danswer， but danswer-stack-inference_model_server-1 and danswer-stack-indexing_model_server-1 could not start successfully
![image](https://github.com/user-attachments/assets/b0b9ce76-0b0a-44d2-9e00-a9173af238ef)
the docker container error log as：
![image](https://github.com/user-attachments/assets/a3f3203f-5375-4f80-acc8-c40c5269a0a2)
how can i solve this problem

**Comment by msarris** [comment]
I get the same error here.

This is a complete dump of the logs:

```
2024-07-15 13:21:58 2024-07-15 11:21:58.551066: I external/local_tsl/tsl/cuda/cudart_stub.cc:31] Could not find cuda drivers on your machine, GPU will not be used.
2024-07-15 13:21:59 2024-07-15 11:21:59.108485: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:9261] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2024-07-15 13:21:59 2024-07-15 11:21:59.108554: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:607] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2024-07-15 13:21:59 2024-07-15 11:21:59.290909: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1515] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2024-07-15 13:21:59 2024-07-15 11:21:59.688694: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
2024-07-15 13:21:59 To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2024-07-15 13:22:03 2024-07-15 11:22:03.462815: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
2024-07-15 13:22:08 Traceback (most recent call last):
2024-07-15 13:22:08   File "/usr/local/bin/uvicorn", line 8, in <module>
2024-07-15 13:22:08     sys.exit(main())
2024-07-15 13:22:08              ^^^^^^
2024-07-15 13:22:08   File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
2024-07-15 13:22:08     return self.main(*args, **kwargs)
2024-07-15 13:22:08            ^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-07-15 13:22:08   File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1078, in main
2024-07-15 13:22:08     rv = self.invoke(ctx)
2024-07-15 13:22:08          ^^^^^^^^^^^^^^^^
2024-07-15 13:22:08   File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
2024-07-15 13:22:08     return ctx.invoke(self.callback, **ctx.params)
2024-07-15 13:22:08            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-07-15 13:22:08   File "/usr/local/lib/python3.11/site-packages/click/core.py", line 783, in invoke
2024-07-15 13:22:08     return __callback(*args, **kwargs)
2024-07-15 13:22:08            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-07-15 13:22:08   File "/usr/local/lib/python3.11/site-packages/uvicorn/main.py", line 403, in main
2024-07-15 13:22:08     run(
2024-07-15 13:22:08   File "/usr/local/lib/python3.11/site-packages/uvicorn/main.py", line 568, in run
2024-07-15 13:22:08     server.run()
2024-07-15 13:22:08   File "/usr/local/lib/python3.11/site-packages/uvicorn/server.py", line 59, in run
2024-07-15 13:22:08     return asyncio.run(self.serve(sockets=sockets))
2024-07-15 13:22:08            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-07-15 13:22:08   File "/usr/local/lib/python3.11/asyncio/runners.py", line 190, in run
2024-07-15 13:22:08     return runner.run(main)
2024-07-15 13:22:08            ^^^^^^^^^^^^^^^^
2024-07-15 13:22:08   File "/usr/local/lib/python3.11/asyncio/runners.py", line 118, in run
2024-07-15 13:22:08     return self._loop.run_until_complete(task)
2024-07-15 13:22:08            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-07-15 13:22:08   File "/usr/local/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
2024-07-15 13:22:08     return future.result()
2024-07-15 13:22:08            ^^^^^^^^^^^^^^^
2024-07-15 13:22:08   File "/usr/local/lib/python3.11/site-packages/uvicorn/server.py", line 66, in serve
2024-07-15 13:22:08     config.load()
2024-07-15 13:22:08   File "/usr/local/lib/python3.11/site-packages/uvicorn/config.py", line 471, in load
2024-07-15 13:22:08     self.loaded_app = import_from_string(self.app)
2024-07-15 13:22:08                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-07-15 13:22:08   File "/usr/local/lib/python3.11/site-packages/uvicorn/importer.py", line 24, in import_from_string
2024-07-15 13:22:08     raise exc from None
2024-07-15 13:22:08   File "/usr/local/lib/python3.11/site-packages/uvicorn/importer.py", line 21, in import_from_string
2024-07-15 13:22:08     module = importlib.import_module(module_str)
2024-07-15 13:22:08              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-07-15 13:22:08   File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
2024-07-15 13:22:08     return _bootstrap._gcd_import(name[level:], package, level)
2024-07-15 13:22:08            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-07-15 13:22:08   File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
2024-07-15 13:22:08   File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
2024-07-15 13:22:08   File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
2024-07-15 13:22:08   File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
2024-07-15 13:22:08   File "<frozen importlib._bootstrap_external>", line 940, in exec_module
2024-07-15 13:22:08   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
2024-07-15 13:22:08   File "/app/model_server/main.py", line 12, in <module>
2024-07-15 13:22:08     from model_server.custom_models import router as custom_models_router
2024-07-15 13:22:08   File "/app/model_server/custom_models.py", line 9, in <module>
2024-07-15 13:22:08     from model_server.constants import MODEL_WARM_UP_STRING
2024-07-15 13:22:08   File "/app/model_server/constants.py", line 3, in <module>
2024-07-15 13:22:08     from danswer.search.enums import EmbedTextType
2024-07-15 13:22:08 ModuleNotFoundError: No module named 'danswer.search'
```

The service just restarts after this and then these logs repeat again.

**Comment by hurrdurrsan** [comment]
I have the same issue since I cloned the current repo and tried to build with Docker

**Comment by Weves** [comment]
@hurrdurrsan, @msarris, @lucashaha this should be fixed now! Let me know if you're still running into any issues after pulling the latest!

**Comment by hurrdurrsan** [comment]
> @hurrdurrsan, @msarris, @lucashaha this should be fixed now! Let me know if you're still running into any issues after pulling the latest!

All good now, thanks! Any chance that you can at least briefly describe the issue and the fix? I am trying to learn
