### ISSUE TITLE
Last message alone is too large!

### ISSUE THREAD

**Issue by lucashaha** [danswer-ai/danswer#1846]
![image](https://github.com/user-attachments/assets/1b491763-719c-4ad6-b43c-cb9e01491c1a)
I have an error like “Last message alone is too large” how to solve it?

**Comment by mkrdip** [comment]
I can confirm this well even with new changes in the codebase. The following errors come from the Azure OpenAI endpoint. 
<img width="419" alt="image" src="https://github.com/user-attachments/assets/4da6949a-4b16-4604-a458-31135c8067b7">

The initial error `Last message alone is too large` used to show before the changes were pushed and still shows when larger documents are uploaded chat to interact with Ollama or local LLM endpoints. 

Surprisingly when I comment this part of the code:  https://github.com/danswer-ai/danswer/blob/87fadb07eabf9983a5e6cf48f61245d04d0fb2d1/backend/danswer/prompts/prompt_utils.py#L146C1-L147C61

**Comment by argauerc** [comment]
Error "Last message alone is too large" when using upload txt file

Danswer Version: 0.5.7
Local Ollama / Model: LLama3.1

Stack Trace
`
Traceback (most recent call last):
  File "/app/danswer/chat/process_message.py", line 654, in stream_chat_message_objects
    for packet in answer.processed_streamed_output:
  File "/app/danswer/llm/answering/answer.py", line 535, in processed_streamed_output
    for processed_packet in _process_stream(output_generator):
  File "/app/danswer/llm/answering/answer.py", line 485, in _process_stream
    for message in stream:
  File "/app/danswer/llm/answering/answer.py", line 389, in _raw_output_for_non_explicit_tool_calling_llms
    prompt = prompt_builder.build()
             ^^^^^^^^^^^^^^^^^^^^^^
  File "/app/danswer/llm/answering/prompts/build.py", line 136, in build
    return drop_messages_history_overflow(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/danswer/prompts/prompt_utils.py", line 180, in drop_messages_history_overflow
    ind_prev_msg_start = find_last_index(
                         ^^^^^^^^^^^^^^^^
  File "/app/danswer/prompts/prompt_utils.py", line 146, in find_last_index
    raise ValueError("Last message alone is too large!")
ValueError: Last message alone is too large!
`

Uploaded text file (size: 21 KB)
![screenshot](https://github.com/user-attachments/assets/b5e20b20-4c27-4a3a-a17e-03808e3ee912)

**Comment by vincentcox** [comment]
Same!

**Comment by dhubai** [comment]
anyone found a solution?

**Comment by palvar32** [comment]
This is still an issue

**Comment by tim-dim** [comment]
I have the issue when using tool calling with gemini-2.0-flash via vertex_ai, but with gemini-1.5-pro via gemini api it works.
