### ISSUE TITLE
Tool 'run_search' not found

### ISSUE THREAD

**Issue by Drewster87** [danswer-ai/danswer#1921]
2024-07-24 14:25:47 api_server-1              | 07/24/2024 07:25:47 PM       token_limit.py 126 : Checking for any rate limits...
2024-07-24 14:25:47 api_server-1              | 07/24/2024 07:25:47 PM      chat_backend.py 289 : Received new chat message: hello
2024-07-24 14:25:47 api_server-1              | INFO:     172.18.0.9:34054 - "POST /chat/send-message HTTP/1.1" 200 OK
2024-07-24 14:25:47 api_server-1              | 07/24/2024 07:25:47 PM   process_message.py 670 : Failed to process chat message
2024-07-24 14:25:47 api_server-1              | Traceback (most recent call last):
2024-07-24 14:25:47 api_server-1              |   File "/app/danswer/chat/process_message.py", line 603, in stream_chat_message_objects
2024-07-24 14:25:47 api_server-1              |     for packet in answer.processed_streamed_output:
2024-07-24 14:25:47 api_server-1              |   File "/app/danswer/llm/answering/answer.py", line 496, in processed_streamed_output
2024-07-24 14:25:47 api_server-1              |     for processed_packet in _process_stream(output_generator):
2024-07-24 14:25:47 api_server-1              |   File "/app/danswer/llm/answering/answer.py", line 447, in _process_stream
2024-07-24 14:25:47 api_server-1              |     for message in stream:
2024-07-24 14:25:47 api_server-1              |   File "/app/danswer/llm/answering/answer.py", line 303, in _raw_output_for_non_explicit_tool_calling_llms
2024-07-24 14:25:47 api_server-1              |     raise RuntimeError(f"Tool '{self.force_use_tool.tool_name}' not found")
2024-07-24 14:25:47 api_server-1              | RuntimeError: Tool 'run_search' not found
2024-07-24 14:25:47 api_server-1              | 07/24/2024 07:25:47 PM            timing.py  74 : stream_chat_message took 0.013679027557373047 seconds

When I try to do a GPT chat, I get the error

Tool 'run_search' not found

but I get no such error when I do a Danswer chat.

**Comment by Drewster87** [comment]
As a follow up I downloaded previous releases and deployed them with my .env until the error resolved.  I only had to go back to v0.4.4
So whatever broke was in the jump from v0.4.4 to v0.4.5 I'd say.

**Comment by Weves** [comment]
Hey @Drewster87 thanks for bringing this up! This should be addressed in https://github.com/danswer-ai/danswer/pull/1928.
