### ISSUE TITLE
_TOKENIZER' is not defined exception in the v0.3.93 version

### ISSUE THREAD

**Issue by yurtalangokhan** [danswer-ai/danswer#2013]
Hi,
When indexing a file with the intfloat/multilingual-e5-large embedding model, it fails and I get the error '_TOKENIZER' is not defined. I am using version v0.3.93. search_nlp_models.py", line 51, in get_default_tokenizer does not recognize tokinezer.

**Full Trace:**
run_indexing.py 338 : [Attempt ID: 37] Indexing job with ID '37' failed due to name '_TOKENIZER' is not defined
Traceback (most recent call last):
File "/app/danswer/background/indexing/run_indexing.py", line 330, in run_indexing_entrypoint
_run_indexing(db_session, attempt)
File "/app/danswer/background/indexing/run_indexing.py", line 256, in _run_indexing
raise e
File "/app/danswer/background/indexing/run_indexing.py", line 190, in _run_indexing
new_docs, total_batch_chunks = indexing_pipeline(
^^^^^^^^^^^^^^^^^^
File "/app/danswer/utils/timing.py", line 31, in wrapped_func
result = func(*args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^
File "/app/danswer/indexing/indexing_pipeline.py", line 155, in index_doc_batch
chain(*[chunker.chunk(document=document) for document in updatable_docs])
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/app/danswer/indexing/indexing_pipeline.py", line 155, in <listcomp>
chain(*[chunker.chunk(document=document) for document in updatable_docs])
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/app/danswer/indexing/chunker.py", line 188, in chunk
return chunk_document(document)
^^^^^^^^^^^^^^^^^^^^^^^^
File "/app/danswer/indexing/chunker.py", line 80, in chunk_document
tokenizer = get_default_tokenizer()
^^^^^^^^^^^^^^^^^^^^^^^
File "/app/danswer/search/search_nlp_models.py", line 51, in get_default_tokenizer
if _TOKENIZER[0] is None or (
^^^^^^^^^^
NameError: name '_TOKENIZER' is not defined
08/01/2024 11:28:18 AM update.py 327 : [Attempt ID: 37] Kicked off indexing attempt for connector: 'FileConnector-1722511848152', with config: '{'file_locations': ['ae28ecf5-365e-42f2-930c-1d21dd81fc11/asd.txt']}', and with credentials: '34'

**Comment by rkuo-danswer** [comment]
It looks like this function and var name no longer exist, so the error is no longer relevant or has been cleaned up in subsequent PR's.  Thank you for your feedback, and please feel free to report any additional issues you run into so we can address them!
