### ISSUE TITLE
Slack Connector issue with Conversations API and 'is_archived'

### ISSUE THREAD

**Issue by chrisedington** [danswer-ai/danswer#205]
The Slack API doesn't like 'is_archived' conversations and we should filter them out.

https://api.slack.com/methods/conversations.join

Slack API doc:
```
Common error response
Typical error response if the conversation is archived and cannot be joined

{
    "ok": false,
    "error": "is_archived"
}
```

```
07/18/2023 03:52:12 PM         connector.py 173 : Pulled 22300 documents from slack channel alerts-trials
07/18/2023 03:52:14 PM            update.py 176 : Indexing job with id 240 failed due to The request to the Slack API failed. (url: https://www.slack.com/api/conversations.join)
The server responded with: {'ok': False, 'error': 'is_archived'}
Traceback (most recent call last):
  File "/app/danswer/background/update.py", line 155, in run_indexing_jobs
    for doc_batch in doc_batch_generator:
  File "/app/danswer/connectors/slack/connector.py", line 293, in poll_source
    for document in get_all_docs(
  File "/app/danswer/connectors/slack/connector.py", line 150, in get_all_docs
    for message_batch in channel_message_batches:
  File "/app/danswer/connectors/slack/connector.py", line 64, in get_channel_messages
    client.conversations_join(
  File "/usr/local/lib/python3.11/site-packages/slack_sdk/web/client.py", line 2453, in conversations_join
    return self.api_call("conversations.join", params=kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/slack_sdk/web/base_client.py", line 156, in api_call
    return self._sync_send(api_url=api_url, req_args=req_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/slack_sdk/web/base_client.py", line 187, in _sync_send
    return self._urllib_api_call(
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/slack_sdk/web/base_client.py", line 317, in _urllib_api_call
    ).validate()
      ^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/slack_sdk/web/slack_response.py", line 199, in validate
    raise e.SlackApiError(message=msg, response=self)
slack_sdk.errors.SlackApiError: The request to the Slack API failed. (url: https://www.slack.com/api/conversations.join)
The server responded with: {'ok': False, 'error': 'is_archived'}
```

**Comment by chrisedington** [comment]
I'm testing a potential fix, I will create a PR if it works as expected.

```
def get_channel_messages(
    client: WebClient,
    channel: dict[str, Any],
    oldest: str | None = None,
    latest: str | None = None,
) -> Generator[list[MessageType], None, None]:
    """Get all messages in a channel"""
    # join so that the bot can access messages
    if not channel["is_member"] and not channel["is_archived"]:
        client.conversations_join(
            channel=channel["id"], is_private=channel["is_private"]
        )

    for result in _make_slack_api_call(
        client.conversations_history,
        channel=channel["id"],
        oldest=oldest,
        latest=latest,
    ):
        yield cast(list[MessageType], result["messages"])
```

**Comment by Weves** [comment]
Good catch! We hadn't tested on slack workspaces with archived channels yet. Approved / merged https://github.com/danswer-ai/danswer/pull/208.

I will say that ideally, in the long term, we would be able to scrape archived channels as well (since they often contain some useful, relevant information), but it doesn't seem like that's possible based on my reading of the Slack API :(
