### ISSUE TITLE
Web connector no longer uses system environment variables for setting proxy

### ISSUE THREAD

**Issue by emerzon** [danswer-ai/danswer#2095]
A attempt to crawl content with the web connector over a proxy fails with the error:

```
Traceback (most recent call last):
  File "/app/danswer/background/indexing/run_indexing.py", line 169, in _run_indexing
    for doc_batch in doc_batch_generator:
  File "/app/danswer/connectors/web/connector.py", line 349, in load_from_state
    raise RuntimeError(last_error)
RuntimeError: Failed to fetch 'https://<redacted>/': Unable to reach https://<redacted>/ - check your internet connection

``` 
It seems to be ignoring the environment variables `HTTP_PROXY` and `HTTPS_PROXY`
Apparently this is a regression as this worked in previous versions

**Comment by emerzon** [comment]
Unable to reproduce each time, closing for further investigation
