### ISSUE TITLE
Embedding settings are not being fully applied

### ISSUE THREAD

**Issue by DavidReinberger** [danswer-ai/danswer#2270]
Even if I correct the mistake described in this issue https://github.com/danswer-ai/danswer/issues/2269, by issuing a fetch request in dev console.

```
fetch("http://192.168.0.131:2354/api/search-settings/update-inference-settings", {
  "headers": {
    "accept": "*/*",
    "accept-language": "cs,en;q=0.9,cs-CZ;q=0.8",
    "cache-control": "no-cache",
    "content-type": "application/json",
    "pragma": "no-cache"
  },
  "referrer": "http://192.168.0.131:2354/admin/embeddings?step=1",
  "referrerPolicy": "strict-origin-when-cross-origin",
  "body": "{\"rerank_api_key\": null, \"api_key\":null,\"num_rerank\":20,\"rerank_provider_type\":null,\"rerank_model_name\":\"mixedbread-ai/mxbai-rerank-xsmall-v1\",\"model_name\":\"intfloat/multilingual-e5-small\",\"model_dim\":768,\"normalize\":true,\"query_prefix\":\"\",\"passage_prefix\":\"search_document: \",\"index_name\":\"danswer_chunk_nomic_ai_nomic_embed_text_v1\",\"multipass_indexing\":true,\"multilingual_expansion\":[\"Czech\",\"English\"],\"disable_rerank_for_streaming\":false}",
  "method": "POST",
  "mode": "cors",
  "credentials": "include"
});
```

Only the reranker is changed and the embedding model stays the same. This also applies to setting the cloud hosted models, where the api server breaks completely, because the index service can't download the model from hugging face.

Fetch Request
```
fetch("http://192.168.0.131:2354/api/search-settings/update-inference-settings", {
  "headers": {
    "accept": "*/*",
    "accept-language": "cs,en;q=0.9,cs-CZ;q=0.8",
    "cache-control": "no-cache",
    "content-type": "application/json",
    "pragma": "no-cache"
  },
  "referrer": "http://192.168.0.131:2354/admin/embeddings?step=2",
  "referrerPolicy": "strict-origin-when-cross-origin",
  "body": "{\"rerank_api_key\":\"KEY\", \"api_key\":\"KEY\",\"num_rerank\":20,\"rerank_provider_type\":\"cohere\",\"rerank_model_name\":\"rerank-multilingual-v3.0\",\"model_name\":\"nomic-ai/nomic-embed-text-v1\",\"model_dim\":768,\"normalize\":true,\"query_prefix\":\"\",\"passage_prefix\":\"search_document: \",\"index_name\":\"danswer_chunk_nomic_ai_nomic_embed_text_v1\",\"multipass_indexing\":true,\"multilingual_expansion\":[\"Czech\",\"English\"],\"disable_rerank_for_streaming\":false,\"provider_type\":\"openai\"}",
  "method": "POST",
  "mode": "cors",
  "credentials": "include"
});
```

Api Error
```
ERROR:    08/30/2024 03:36:18 PM           search_nlp_models.py  315: Attempt 3 failed; retrying in 5 seconds...
Traceback (most recent call last):
  File "/app/danswer/natural_language_processing/search_nlp_models.py", line 312, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/app/danswer/natural_language_processing/search_nlp_models.py", line 260, in predict
    response.raise_for_status()
  File "/usr/local/lib/python3.11/site-packages/requests/models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: http://inference_model_server:9000/encoder/cross-encoder-scores
```

Inference Service Error
```
Repository Not Found for url: https://huggingface.co/rerank-multilingual-v3.0/resolve/main/config.json.
Please make sure you specified the correct `repo_id` and `repo_type`.
If you are trying to access a private or gated repo, make sure you are authenticated.
Invalid username or password.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/app/model_server/encoders.py", line 371, in process_rerank_request
    sim_scores = local_rerank(
                 ^^^^^^^^^^^^^
  File "/app/model_server/utils.py", line 27, in wrapped_func
    result = func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^
  File "/app/model_server/encoders.py", line 308, in local_rerank
    cross_encoder = get_local_reranking_model(model_name)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/model_server/encoders.py", line 233, in get_local_reranking_model
    model = CrossEncoder(model_name)
            ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sentence_transformers/cross_encoder/CrossEncoder.py", line 58, in __init__
    self.config = AutoConfig.from_pretrained(model_name, revision=revision)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/transformers/models/auto/configuration_auto.py", line 1138, in from_pretrained
    config_dict, unused_kwargs = PretrainedConfig.get_config_dict(pretrained_model_name_or_path, **kwargs)
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/transformers/configuration_utils.py", line 631, in get_config_dict
    config_dict, kwargs = cls._get_config_dict(pretrained_model_name_or_path, **kwargs)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/transformers/configuration_utils.py", line 686, in _get_config_dict
    resolved_config_file = cached_file(
                           ^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/transformers/utils/hub.py", line 421, in cached_file
    raise EnvironmentError(
OSError: rerank-multilingual-v3.0 is not a local folder and is not a valid model identifier listed on 'https://huggingface.co/models'
If this is a private repository, make sure to pass a token having permission to this repo either by logging in with `huggingface-cli login` or by passing `token=<your_token>`
```

**Comment by pablodanswer** [comment]
Hey @DavidReinberger the `/update-inference` route is explicitly for updating settings that won't necessitate a re-indexing, so it's expected that that endpoint doesn't modify the current embedding model.  The other issue you mentioned is covered in the PR I mentioned - hope that that helps!

**Comment by pablodanswer** [comment]
Resolved with https://github.com/danswer-ai/danswer/pull/2259

**Comment by DavidReinberger** [comment]
@pablodanswer thanks for the answer, tried to use the `set-new-search-settings` endpoint, which works but I guess I'm not sending the right values for `model_dim`, `passage_prefix` or `query_prefix`. Any idea?

```
{
    "rerank_api_key": "API_KEY",
    "num_rerank": 20,
    "rerank_provider_type": "cohere",
    "rerank_model_name": "rerank-multilingual-v3.0",
    "model_name": "text-embedding-3-small",
    "model_dim": 768,
    "normalize": true,
    "query_prefix": "",
    "passage_prefix": "",
    "index_name": "danswer_chunk",
    "multipass_indexing": true,
    "multilingual_expansion": [
        "Czech",
        "English"
    ],
    "disable_rerank_for_streaming": false,
    "provider_type": "openai"
}
```

This is the thrown error in the ui


```
raceback (most recent call last):
  File "/app/danswer/background/indexing/run_indexing.py", line 219, in _run_indexing
    new_docs, total_batch_chunks = indexing_pipeline(
                                   ^^^^^^^^^^^^^^^^^^
  File "/app/danswer/indexing/indexing_pipeline.py", line 140, in index_doc_batch_with_handler
    r = index_doc_batch(
        ^^^^^^^^^^^^^^^^
  File "/app/danswer/utils/timing.py", line 31, in wrapped_func
    result = func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^
  File "/app/danswer/indexing/indexing_pipeline.py", line 329, in index_doc_batch
    insertion_records = document_index.index(chunks=access_aware_chunks)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/danswer/document_index/vespa/index.py", line 225, in index
    batch_index_vespa_chunks(
  File "/app/danswer/document_index/vespa/indexing_utils.py", line 208, in batch_index_vespa_chunks
    future.result()
  File "/usr/local/lib/python3.11/concurrent/futures/_base.py", line 449, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/retry/api.py", line 73, in retry_decorator
    return __retry_internal(partial(f, *args, **kwargs), exceptions, tries, delay, max_delay, backoff, jitter,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/retry/api.py", line 33, in __retry_internal
    return f()
           ^^^
  File "/app/danswer/document_index/vespa/indexing_utils.py", line 186, in _index_vespa_chunk
    raise e
  File "/app/danswer/document_index/vespa/indexing_utils.py", line 181, in _index_vespa_chunk
    res.raise_for_status()
  File "/usr/local/lib/python3.11/site-packages/httpx/_models.py", line 749, in raise_for_status
    raise HTTPStatusError(message, request=request, response=self)
httpx.HTTPStatusError: Server error '500 Server Error' for url 'http://index:8081/document/v1/default/danswer_chunk/docid/449c6ade-d73f-57ba-afa7-9d78ba7635e2'
```
