### ISSUE TITLE
GPT4ALL 1.0.5 not available on Macbook Pro M1 

### ISSUE THREAD

**Issue by chrisedington** [danswer-ai/danswer#232]
Looks like there is no Arm64 build of GPT4ALL after `0.1.7`.

When I downgrade to `0.1.7` it builds, but it's probably going to generate a few issues here - so here's an issue for tracking.

Solution for now:

Downgrade gpt4all in `backend/requirements/default.txt` to `0.1.7`

Further issue causes the stack not to start when using `0.1.7` - perhaps we could switch off GPT4ALL in `backend/danswer/configs/app_configs.py` ?

```
danswer-stack-api_server-1     | Traceback (most recent call last):
danswer-stack-api_server-1     |   File "/usr/local/bin/uvicorn", line 8, in <module>
danswer-stack-api_server-1     |     sys.exit(main())
danswer-stack-api_server-1     |              ^^^^^^
danswer-stack-api_server-1     |   File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
danswer-stack-api_server-1     |     return self.main(*args, **kwargs)
danswer-stack-api_server-1     |            ^^^^^^^^^^^^^^^^^^^^^^^^^^
danswer-stack-api_server-1     |   File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1078, in main
danswer-stack-api_server-1     |     rv = self.invoke(ctx)
danswer-stack-api_server-1     |          ^^^^^^^^^^^^^^^^
danswer-stack-api_server-1     |   File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
danswer-stack-api_server-1     |     return ctx.invoke(self.callback, **ctx.params)
danswer-stack-api_server-1     |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
danswer-stack-api_server-1     |   File "/usr/local/lib/python3.11/site-packages/click/core.py", line 783, in invoke
danswer-stack-api_server-1     |     return __callback(*args, **kwargs)
danswer-stack-api_server-1     |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
danswer-stack-api_server-1     |   File "/usr/local/lib/python3.11/site-packages/uvicorn/main.py", line 403, in main
danswer-stack-api_server-1     |     run(
danswer-stack-api_server-1     |   File "/usr/local/lib/python3.11/site-packages/uvicorn/main.py", line 568, in run
danswer-stack-api_server-1     |     server.run()
danswer-stack-api_server-1     |   File "/usr/local/lib/python3.11/site-packages/uvicorn/server.py", line 59, in run
danswer-stack-api_server-1     |     return asyncio.run(self.serve(sockets=sockets))
danswer-stack-api_server-1     |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
danswer-stack-api_server-1     |   File "/usr/local/lib/python3.11/asyncio/runners.py", line 190, in run
danswer-stack-api_server-1     |     return runner.run(main)
danswer-stack-api_server-1     |            ^^^^^^^^^^^^^^^^
danswer-stack-api_server-1     |   File "/usr/local/lib/python3.11/asyncio/runners.py", line 118, in run
danswer-stack-api_server-1     |     return self._loop.run_until_complete(task)
danswer-stack-api_server-1     |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
danswer-stack-api_server-1     |   File "/usr/local/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
danswer-stack-api_server-1     |     return future.result()
danswer-stack-api_server-1     |            ^^^^^^^^^^^^^^^
danswer-stack-api_server-1     |   File "/usr/local/lib/python3.11/site-packages/uvicorn/server.py", line 66, in serve
danswer-stack-api_server-1     |     config.load()
danswer-stack-api_server-1     |   File "/usr/local/lib/python3.11/site-packages/uvicorn/config.py", line 471, in load
danswer-stack-api_server-1     |     self.loaded_app = import_from_string(self.app)
danswer-stack-api_server-1     |                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
danswer-stack-api_server-1     |   File "/usr/local/lib/python3.11/site-packages/uvicorn/importer.py", line 21, in import_from_string
danswer-stack-api_server-1     |     module = importlib.import_module(module_str)
danswer-stack-api_server-1     |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
danswer-stack-api_server-1     |   File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
danswer-stack-api_server-1     |     return _bootstrap._gcd_import(name[level:], package, level)
danswer-stack-api_server-1     |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
danswer-stack-api_server-1     |   File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
danswer-stack-api_server-1     |   File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
danswer-stack-api_server-1     |   File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
danswer-stack-api_server-1     |   File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
danswer-stack-api_server-1     |   File "<frozen importlib._bootstrap_external>", line 940, in exec_module
danswer-stack-api_server-1     |   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
danswer-stack-api_server-1     |   File "/app/danswer/main.py", line 26, in <module>
danswer-stack-api_server-1     |     from danswer.direct_qa import get_default_backend_qa_model
danswer-stack-api_server-1     |   File "/app/danswer/direct_qa/__init__.py", line 6, in <module>
danswer-stack-api_server-1     |     from danswer.direct_qa.gpt_4_all import GPT4AllChatCompletionQA
danswer-stack-api_server-1     |   File "/app/danswer/direct_qa/gpt_4_all.py", line 18, in <module>
danswer-stack-api_server-1     |     from gpt4all import GPT4All  # type:ignore
danswer-stack-api_server-1     |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^
danswer-stack-api_server-1     |   File "/usr/local/lib/python3.11/site-packages/gpt4all/__init__.py", line 1, in <module>
danswer-stack-api_server-1     |     from . import gpt4all # noqa
danswer-stack-api_server-1     |     ^^^^^^^^^^^^^^^^^^^^^
danswer-stack-api_server-1     |   File "/usr/local/lib/python3.11/site-packages/gpt4all/gpt4all.py", line 6, in <module>
danswer-stack-api_server-1     |     from . import pyllmodel
danswer-stack-api_server-1     |   File "/usr/local/lib/python3.11/site-packages/gpt4all/pyllmodel.py", line 39, in <module>
danswer-stack-api_server-1     |     llmodel, llama = load_llmodel_library()
danswer-stack-api_server-1     |                      ^^^^^^^^^^^^^^^^^^^^^^
danswer-stack-api_server-1     |   File "/usr/local/lib/python3.11/site-packages/gpt4all/pyllmodel.py", line 32, in load_llmodel_library
danswer-stack-api_server-1     |     llama_lib = ctypes.CDLL(llama_dir, mode=ctypes.RTLD_GLOBAL)
danswer-stack-api_server-1     |                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
danswer-stack-api_server-1     |   File "/usr/local/lib/python3.11/ctypes/__init__.py", line 376, in __init__
danswer-stack-api_server-1     |     self._handle = _dlopen(self._name, mode)
danswer-stack-api_server-1     |                    ^^^^^^^^^^^^^^^^^^^^^^^^^
danswer-stack-api_server-1     | OSError: /usr/local/lib/python3.11/site-packages/gpt4all/llmodel_DO_NOT_MODIFY/build/libllama.so: cannot open shared object file: No such file or directory
danswer-stack-api_server-1 exited with code 0
```

**Comment by sidravi1** [comment]
What about creating a conda env and emulating x86 with something like:

`CONDA_SUBDIR=osx-64 conda create -n myenv python=3.9` 

Probably take a small performance hit but should work.

**Comment by cnh** [comment]
@sidravi1 have you tried this fix ?

> What about creating a conda env and emulating x86 with something like:
> 
> `CONDA_SUBDIR=osx-64 conda create -n myenv python=3.9`
> 
> Probably take a small performance hit but should work.

**Comment by yuhongsun96** [comment]
Closing due to inactivity.

GPT4All is by default disabled, Danswer checks if the library is installed during startup. You'll have to install it yourself first though before using it.

The prebuilt containers also will not contain it.

Details on configuring it for use can be found here:
https://docs.danswer.dev/gen_ai_configs/gpt_4_all
