### ISSUE TITLE
How to use proxy to valid OenAI api eky

### ISSUE THREAD

**Issue by ws1hope** [danswer-ai/danswer#240]
I need to use proxy to valid OpenAI api key.
I modify docker_compose.dev.yml as follow:
`environment:
      - http_proxy=http://XXXX
      - https_proxy=http://XXXX`
above operation is operated on every image.
However, I can open the web, but the backend still report error.
How can i set internet proxy to valid openai api key correctly.

**Comment by yuhongsun96** [comment]
This is not officially supported, why do you need this?
Is this an environment variable you are passing into the container? What is expected to be picking this up?

**Comment by veryspicy** [comment]
we can't access openai directly in some countries and need to use a proxy,   if we deploy the Danswer with docker, the docker container "danswer-api_server" can't validate the openai api key via host proxy,  so need to add proxy config into env.  if you just add the below config in env, the api server can't start,  from the log you will get error like bellow.
environment: - http_proxy=http://XXXX - https_proxy=http://XXXX

ERROR:    Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 677, in lifespan
    async with self.lifespan_context(app) as maybe_state:
  File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 566, in __aenter__
    await self._router.startup()
  File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 656, in startup
    handler()
  File "/app/danswer/main.py", line 191, in startup_event
    collection.name for collection in list_qdrant_collections().collections
                                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/danswer/datastores/qdrant/indexing.py", line 39, in list_qdrant_collections
    return get_qdrant_client().get_collections()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/qdrant_client/qdrant_client.py", line 1130, in get_collections
    return self._client.get_collections(**kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/qdrant_client/qdrant_remote.py", line 1501, in get_collections
    ] = self.http.collections_api.get_collections().result
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/qdrant_client/http/api/collections_api.py", line 931, in get_collections
    return self._build_for_get_collections()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/qdrant_client/http/api/collections_api.py", line 379, in _build_for_get_collections
    return self.api_client.request(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/qdrant_client/http/api_client.py", line 68, in request
    return self.send(request, type_)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/qdrant_client/http/api_client.py", line 91, in send
    raise UnexpectedResponse.for_response(response)
qdrant_client.http.exceptions.UnexpectedResponse: Unexpected Response: 502 (Bad Gateway)



remedy:
you need to add no_proxy, filter some internal services access bypass the proxy,  raw.githubusercontent.com, typesense  mabe not need, you can remove by yourself.
environment:
      - http_proxy=http://ip:port
      - https_proxy=http://ip:port
      - no_proxy=127.0.0.1,localhost,vector_db,huggingface.co,search_engine,raw.githubusercontent.com,typesense

from proxy server log, just confirm only openai address appear:
INFO[2351] [TCP] 172.30.0.5:41222 --> api.openai.com:443 match DomainSuffix(openai.com)
