### ISSUE TITLE
Slack slash command /DanswerBot stopped working

### ISSUE THREAD

**Issue by mmanolakeris** [danswer-ai/danswer#2428]
While channel message works normally, when sending a slash command /DanswerBot the following error shows up in the background server.
This was not the case in the past and it suddenly stopped working.

`2024-09-13 10:48:12 background-1              | ERROR:    09/13/2024 08:48:11 AM                    listener.py  438: Failed to process slack event
2024-09-13 10:48:12 background-1              | Traceback (most recent call last):
2024-09-13 10:48:12 background-1              |   File "/app/danswer/danswerbot/slack/listener.py", line 436, in process_slack_event
2024-09-13 10:48:12 background-1              |     return process_message(req, client)
2024-09-13 10:48:12 background-1              |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-09-13 10:48:12 background-1              |   File "/app/danswer/danswerbot/slack/listener.py", line 374, in process_message
2024-09-13 10:48:12 background-1              |     failed = handle_message(
2024-09-13 10:48:12 background-1              |              ^^^^^^^^^^^^^^^
2024-09-13 10:48:12 background-1              |   File "/app/danswer/danswerbot/slack/handlers/handle_message.py", line 226, in handle_message
2024-09-13 10:48:12 background-1              |     issue_with_regular_answer = handle_regular_answer(
2024-09-13 10:48:12 background-1              |                                 ^^^^^^^^^^^^^^^^^^^^^^
2024-09-13 10:48:12 background-1              |   File "/app/danswer/danswerbot/slack/handlers/handle_regular_answer.py", line 132, in handle_regular_answer
2024-09-13 10:48:12 background-1              |     raise RuntimeError(
2024-09-13 10:48:12 background-1              | RuntimeError: No message timestamp to respond to in `handle_message`. This should never happen`

**Comment by pablodanswer** [comment]
Thank you for bringing this up - Resolved by https://github.com/danswer-ai/danswer/pull/2436
