### ISSUE TITLE
Indexing Failure (Confluence): TypeError

### ISSUE THREAD

**Issue by emerzon** [danswer-ai/danswer#2454]
```
Traceback (most recent call last):
  File "/app/danswer/background/indexing/run_indexing.py", line 179, in _run_indexing
    for doc_batch in connector_runner.run():
  File "/app/danswer/connectors/connector_runner.py", line 48, in run
    yield from self.doc_batch_generator
  File "/app/danswer/connectors/confluence/connector.py", line 812, in poll_source
    doc_batch, unused_attachments_batch, num_pages = self._get_doc_batch(
                                                     ^^^^^^^^^^^^^^^^^^^^
  File "/app/danswer/connectors/confluence/connector.py", line 680, in _get_doc_batch
    page_text += comments_text
TypeError: can only concatenate str (not "NoneType") to str
```

**Comment by emerzon** [comment]
Closing as no longer reproducible in current version
