### ISSUE TITLE
Indexing Failure: Timeout while requesting OpenAI embeddings

### ISSUE THREAD

**Issue by emerzon** [danswer-ai/danswer#2456]
The issue happens sometimes with large embeddings requests. The request times out before the API is able to respond.

A timeout parameter should be created to allow more time for the API response.

```
Traceback (most recent call last):
  File "/app/model_server/encoders.py", line 404, in process_embed_request
    embeddings = embed_text(
                 ^^^^^^^^^^^
  File "/app/model_server/utils.py", line 27, in wrapped_func
    result = func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^
  File "/app/model_server/encoders.py", line 311, in embed_text
    embeddings = cloud_model.embed(
                 ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/retry/api.py", line 73, in retry_decorator
    return __retry_internal(partial(f, *args, **kwargs), exceptions, tries, delay, max_delay, backoff, jitter,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/retry/api.py", line 33, in __retry_internal
    return f()
           ^^^
  File "/app/model_server/encoders.py", line 185, in embed
    raise HTTPException(
fastapi.exceptions.HTTPException: 500: Error embedding text with EmbeddingProvider.OPENAI: Error embedding text with OpenAI: Request timed out. 
Model: text-embedding-3-large 
Provider: EmbeddingProvider.OPENAI 
```

**Comment by emerzon** [comment]
Fixed by #2460
