### ISSUE TITLE
"Application error: a client-side exception has occurred (see the browser console for more information)."

### ISSUE THREAD

**Issue by med4u** [danswer-ai/danswer#2517]
Hi, thank you for this great software!
Error and unusable since latest update (actual c82a36ad6882c7c83334f0e6a30eeb62a2aba651)
Could someone fix it?

Main /chat page shows : 

> Application error: a client-side exception has occurred (see the browser console for more information).

Console log : 

> danswer-stack-api_server-1              | INFO:     09/20/2024 09:15:34 AM                    h11_impl.py  499: 172.26.0.9:5479
> 6 - "GET /settings HTTP/1.1" 200
> danswer-stack-nginx-1                   | 192.168.1.6 - - [20/Sep/2024:09:15:34 +0000] "GET / HTTP/1.1" 307 2710 "-" "Mozilla/5
> .0 (Macintosh; Intel Mac OS X 10.15; rv:130.0) Gecko/20100101 Firefox/130.0" "-" rt=0.101
> danswer-stack-api_server-1              | INFO:     09/20/2024 09:15:34 AM                    h11_impl.py  499: 172.26.0.9:5479
> 6 - "GET /auth/type HTTP/1.1" 200
> danswer-stack-api_server-1              | INFO:     09/20/2024 09:15:34 AM                    h11_impl.py  499: 172.26.0.9:5486
> 0 - "GET /query/valid-tags HTTP/1.1" 200
> danswer-stack-api_server-1              | INFO:     09/20/2024 09:15:34 AM                    h11_impl.py  499: 172.26.0.9:5488
> 8 - "GET /folder HTTP/1.1" 200
> danswer-stack-api_server-1              | INFO:     09/20/2024 09:15:34 AM                    h11_impl.py  499: 172.26.0.9:5481
> 2 - "GET /me HTTP/1.1" 200
> danswer-stack-api_server-1              | INFO:     09/20/2024 09:15:34 AM                    h11_impl.py  499: 172.26.0.9:5485
> 0 - "GET /chat/get-user-chat-sessions HTTP/1.1" 200 
> danswer-stack-api_server-1              | INFO:     09/20/2024 09:15:34 AM                    h11_impl.py  499: 172.26.0.9:5487
> 6 - "GET /llm/provider HTTP/1.1" 200
> danswer-stack-api_server-1              | INFO:     09/20/2024 09:15:34 AM                    h11_impl.py  499: 172.26.0.9:5489
> 6 - "GET /input_prompt?include_public=true HTTP/1.1" 200
> danswer-stack-api_server-1              | ERROR:    09/20/2024 09:15:34 AM                        main.py  158: ValueError
> danswer-stack-api_server-1              | Traceback (most recent call last):
> danswer-stack-api_server-1              |   File "/app/danswer/main.py", line 155, in value_error_handler
> danswer-stack-api_server-1              |     raise (exc)
> danswer-stack-api_server-1              |   File "/usr/local/lib/python3.11/site-packages/starlette/_exception_handler.py", lin
> e 53, in wrapped_app
> danswer-stack-api_server-1              |     await app(scope, receive, sender)
> danswer-stack-api_server-1              |   File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 74, in ap
> p
> danswer-stack-api_server-1              |     response = await func(request)
> danswer-stack-api_server-1              |                ^^^^^^^^^^^^^^^^^^^
> danswer-stack-api_server-1              |   File "/usr/local/lib/python3.11/site-packages/fastapi/routing.py", line 299, in app
> danswer-stack-api_server-1              |     raise e
> danswer-stack-api_server-1              |   File "/usr/local/lib/python3.11/site-packages/fastapi/routing.py", line 294, in app
> danswer-stack-api_server-1              |     raw_response = await run_endpoint_function(
> danswer-stack-api_server-1              |                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> danswer-stack-api_server-1              |   File "/usr/local/lib/python3.11/site-packages/fastapi/routing.py", line 193, in run
> _endpoint_function
> danswer-stack-api_server-1              |     return await run_in_threadpool(dependant.call, **values)
> danswer-stack-api_server-1              |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> danswer-stack-api_server-1              |   File "/usr/local/lib/python3.11/site-packages/starlette/concurrency.py", line 42, i
> n run_in_threadpool
> danswer-stack-api_server-1              |     return await anyio.to_thread.run_sync(func, *args)
> danswer-stack-api_server-1              |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> danswer-stack-api_server-1              |   File "/usr/local/lib/python3.11/site-packages/anyio/to_thread.py", line 56, in run_
> sync
> danswer-stack-api_server-1              |     return await get_async_backend().run_sync_in_worker_thread(
> danswer-stack-api_server-1              |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> danswer-stack-api_server-1              |   File "/usr/local/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 23
> 57, in run_sync_in_worker_thread
> danswer-stack-api_server-1              |     return await future
> danswer-stack-api_server-1              |            ^^^^^^^^^^^^
> danswer-stack-api_server-1              |   File "/usr/local/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 86
> 4, in run
> danswer-stack-api_server-1              |     result = context.run(func, *args)
> danswer-stack-api_server-1              |              ^^^^^^^^^^^^^^^^^^^^^^^^
> danswer-stack-api_server-1              |   File "/app/danswer/server/features/persona/api.py", line 220, in list_personas
> danswer-stack-api_server-1              |     return [
> danswer-stack-api_server-1              |            ^
> danswer-stack-api_server-1              |   File "/app/danswer/server/features/persona/api.py", line 221, in <listcomp>
> danswer-stack-api_server-1              |     PersonaSnapshot.from_model(persona)
> danswer-stack-api_server-1              |   File "/app/danswer/server/features/persona/models.py", line 81, in from_model
> danswer-stack-api_server-1              |     return PersonaSnapshot(
> danswer-stack-api_server-1              |            ^^^^^^^^^^^^^^^^
> danswer-stack-api_server-1              |   File "/usr/local/lib/python3.11/site-packages/pydantic/main.py", line 193, in __ini
> t__
> danswer-stack-api_server-1              |     self.__pydantic_validator__.validate_python(data, self_instance=self)
> danswer-stack-api_server-1              | pydantic_core._pydantic_core.ValidationError: 1 validation error for PersonaSnapshot
> danswer-stack-api_server-1              | is_default_persona
> danswer-stack-api_server-1              |   Input should be a valid boolean [type=bool_type, input_value=None, input_type=NoneT
> ype]
> danswer-stack-api_server-1              |     For further information visit https://errors.pydantic.dev/2.8/v/bool_type
> danswer-stack-api_server-1              | INFO:     09/20/2024 09:15:34 AM                    h11_impl.py  499: 172.26.0.9:5484
> 4 - "GET /persona HTTP/1.1" 400
> danswer-stack-api_server-1              | INFO:     09/20/2024 09:15:34 AM                    h11_impl.py  499: 172.26.0.9:5491
> 0 - "GET /settings HTTP/1.1" 200
> danswer-stack-api_server-1              | INFO:     09/20/2024 09:15:34 AM                    h11_impl.py  499: 172.26.0.9:5482
> 4 - "GET /manage/indexing-status HTTP/1.1" 200
> danswer-stack-api_server-1              | INFO:     09/20/2024 09:15:34 AM                    h11_impl.py  499: 172.26.0.9:54832 - "GET /manage/document-set HTTP/1.1" 200
> danswer-stack-web_server-1              | Failed to fetch assistants - Unknown Error
> danswer-stack-web_server-1              | TypeError: Cannot read properties of undefined (reading 'tools')
> danswer-stack-web_server-1              |     at k (/app/.next/server/chunks/5084.js:1:5977)
> danswer-stack-web_server-1              |     at N (/app/.next/server/chunks/5084.js:1:5949)
> danswer-stack-web_server-1              |     at /app/.next/server/app/chat/page.js:107:15779
> danswer-stack-web_server-1              |     at nt (/app/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:38746)
> danswer-stack-web_server-1              |     at Object.useState (/app/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:40703)
> danswer-stack-web_server-1              |     at t.useState (/app/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:110091)
> danswer-stack-web_server-1              |     at eL (/app/.next/server/app/chat/page.js:107:15766)
> danswer-stack-web_server-1              |     at nj (/app/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:46251)
> danswer-stack-web_server-1              |     at nM (/app/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:47571)
> danswer-stack-web_server-1              |     at nN (/app/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:64546) {
> danswer-stack-web_server-1              |   digest: '2557151770'
> danswer-stack-web_server-1              | }
> 

admin/assistants page shows : 

> 
> Something went wrong :(
> 
> Failed to fetch personas - {"message":"1 validation error for PersonaSnapshot\nis_default_persona\n Input should be a valid boolean [type=bool_type, input_value=None, input_type=NoneType]\n For further information visit https://errors.pydantic.dev/2.8/v/bool_type"}

I also tried to downgrade but it showed lot of errors in console. any help with this? It work at ef104e9a82783d4b7db74ea873027c26dbf3ce31 state)

**Comment by med4u** [comment]
browser console log is not very informative : 

> GET
> https://iacapable.fr/chat
> [HTTP/1.1 500 Internal Server Error 232ms]
>

**Comment by med4u** [comment]
GET
https://test.fr/chat
[HTTP/1.1 500 Internal Server Error 232ms]
