### ISSUE TITLE
timestamp too large to convert to C _PyTime_t

### ISSUE THREAD

**Issue by data-source** [danswer-ai/danswer#2567]
New issue with latest 0.6.0-Beta.1, Confluence on-prem connector: timestamp too large to convert to C _PyTime_t

`Traceback (most recent call last):
  File "/app/danswer/connectors/confluence/rate_limit_handler.py", line 33, in wrapped_call
    return confluence_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/atlassian/confluence.py", line 381, in get_page_labels
    response = self.get(url, params=params)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/atlassian/rest_client.py", line 285, in get
    response = self.request(
               ^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/atlassian/rest_client.py", line 257, in request
    self.raise_for_status(response)
  File "/usr/local/lib/python3.11/site-packages/atlassian/confluence.py", line 3091, in raise_for_status
    raise HTTPError(error_msg, response=response)
requests.exceptions.HTTPError: Rate limit exceeded.
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/app/danswer/background/indexing/run_indexing.py", line 179, in _run_indexing
    for doc_batch in connector_runner.run():
  File "/app/danswer/connectors/connector_runner.py", line 48, in run
    yield from self.doc_batch_generator
  File "/app/danswer/connectors/confluence/connector.py", line 769, in poll_source
    doc_batch, unused_attachments_batch, num_pages = self._get_doc_batch(
                                                     ^^^^^^^^^^^^^^^^^^^^
  File "/app/danswer/connectors/confluence/connector.py", line 611, in _get_doc_batch
    page_labels = self._fetch_labels(self.confluence_client, page_id)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/danswer/connectors/confluence/connector.py", line 489, in _fetch_labels
    raise e
  File "/app/danswer/connectors/confluence/connector.py", line 485, in _fetch_labels
    labels_response = get_page_labels(page_id)
                      ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/danswer/connectors/confluence/rate_limit_handler.py", line 56, in wrapped_call
    time.sleep(retry_after)
OverflowError: timestamp too large to convert to C _PyTime_t`

**Comment by rkuo-danswer** [comment]
I can add a quick check for this, but do you happen to have any log line before that that would show what number we parsed for retry-after header? 

AKA

logger.warning(
    f"Rate limit hit. Retrying after {retry_after} seconds..."
)

**Comment by rkuo-danswer** [comment]
PR https://github.com/danswer-ai/danswer/pull/2570 will address this

**Comment by data-source** [comment]
Sure, what would be the best way to get that information>? (docker logs, grep, docker exec, which instance in the stack?)

**Comment by rkuo-danswer** [comment]
This should be in the logs for the background container.
