### ISSUE TITLE
When I use docker to quick start, it can not work

### ISSUE THREAD

**Issue by zhangyanrui** [danswer-ai/danswer#262]
My command is:
```shell
docker compose -f docker-compose.dev.yml -p danswer-stack up -d --pull always --force-recreate
```

Then, it can not work well like this:

<img width="1790" alt="image" src="https://github.com/danswer-ai/danswer/assets/1712032/428f7276-b93e-4751-9d2e-d55b9bb61775">

GET http://192.168.1.6:3000/api/manage/admin/connector/indexing-status 502 (Bad Gateway)

GET http://192.168.1.6:3000/api/manage/admin/connector/indexing-status 502 (Bad Gateway)

GET http://192.168.1.6:3000/api/health 502 (Bad Gateway)

My Docker ls:
<img width="1876" alt="image" src="https://github.com/danswer-ai/danswer/assets/1712032/f2c85107-b28e-4c69-84fb-fad789a95c8a">

**Comment by zhangyanrui** [comment]
I found that one docker can not work, the docker log is :
Traceback (most recent call last):
  File "/usr/local/bin/uvicorn", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/uvicorn/main.py", line 403, in main
    run(
  File "/usr/local/lib/python3.11/site-packages/uvicorn/main.py", line 568, in run
    server.run()
  File "/usr/local/lib/python3.11/site-packages/uvicorn/server.py", line 59, in run
    return asyncio.run(self.serve(sockets=sockets))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/uvicorn/server.py", line 66, in serve
    config.load()
  File "/usr/local/lib/python3.11/site-packages/uvicorn/config.py", line 471, in load
    self.loaded_app = import_from_string(self.app)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/uvicorn/importer.py", line 21, in import_from_string
    module = importlib.import_module(module_str)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/app/danswer/main.py", line 12, in <module>
    from danswer.auth.users import auth_backend
  File "/app/danswer/auth/users.py", line 208, in <module>
    raise AssertionError(f"Invalid OAUTH type {OAUTH_TYPE}")
AssertionError: Invalid OAUTH type

**Comment by freitzzz** [comment]
see this issue: https://github.com/danswer-ai/danswer/issues/260 and apply my patch

**Comment by Weves** [comment]
This should be fixed by https://github.com/danswer-ai/danswer/pull/264! Thanks for bringing this up and @freitzzz for the patch.

**Comment by zhangyanrui** [comment]
Thanks!

**Comment by zhangyanrui** [comment]
still have error now.
<img width="1473" alt="image" src="https://github.com/danswer-ai/danswer/assets/1712032/7d2e01ee-4990-447d-9399-b04be00d639f">

this docker exit with these infos:
Illegal instruction (core dumped)
INFO  [alembic.runtime.migration] Context impl PostgresqlImpl.
INFO  [alembic.runtime.migration] Will assume transactional DDL.
Starting Danswer Api Server
Illegal instruction (core dumped)
INFO  [alembic.runtime.migration] Context impl PostgresqlImpl.
INFO  [alembic.runtime.migration] Will assume transactional DDL.
Starting Danswer Api Server

**Comment by ayush-bharti** [comment]
@zhangyanrui - were you able to resolve this? I am getting the same error. Thanks!

**Comment by zhangyanrui** [comment]
> @zhangyanrui - were you able to resolve this? I am getting the same error. Thanks!

NO， I have already give up.

**Comment by Weves** [comment]
> Illegal instruction (core dumped)

This is usually the result of a CPU which does not support the AVX2 instruction set (which tensorflow requires). What CPU were you running Danswer on?

**Comment by ayush-bharti** [comment]
@Weves - thanks for your comment. It pointed me in the right direction. I was running this in a Proxmox VM, with a fresh Ubuntu server install. Seems I had to select a different CPU type (host) to expose AVX2 instruction set. 

While I am still getting backend not available. It seems that's because of a different issue. I am going to look up if someone else had the other issue and try to resolve it. If I am unable to find any direction, I will create an issue.

Thanks!
