### ISSUE TITLE
i request 10 questions about all my 198 files but something wrong

### ISSUE THREAD

**Issue by johnfelipe** [danswer-ai/danswer#2685]
An unexpected error occurred while processing your request. Please try again later.Show stack trace.

    Traceback (most recent call last):
      File "/usr/local/lib/python3.11/site-packages/litellm/utils.py", line 8154, in __next__
        chunk = next(self.completion_stream)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/usr/local/lib/python3.11/site-packages/litellm/llms/anthropic/chat/handler.py", line 783, in __next__
        return self.chunk_parser(chunk=data_json)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/usr/local/lib/python3.11/site-packages/litellm/llms/anthropic/chat/handler.py", line 743, in chunk_parser
        raise AnthropicError(
    litellm.llms.anthropic.common_utils.AnthropicError: Overloaded
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/app/danswer/chat/process_message.py", line 671, in stream_chat_message_objects
        for packet in answer.processed_streamed_output:
      File "/app/danswer/llm/answering/answer.py", line 578, in processed_streamed_output
        for processed_packet in _process_stream(output_generator):
      File "/app/danswer/llm/answering/answer.py", line 572, in _process_stream
        yield from process_answer_stream_fn(_stream())
      File "/app/danswer/llm/answering/stream_processing/citation_processing.py", line 218, in stream_processor
        yield from extract_citations_from_stream(
      File "/app/danswer/llm/answering/stream_processing/citation_processing.py", line 71, in extract_citations_from_stream
        for raw_token in tokens:
      File "/app/danswer/llm/answering/answer.py", line 558, in _stream
        for item in itertools.chain([message], stream):
      File "/app/danswer/llm/answering/answer.py", line 483, in _raw_output_for_non_explicit_tool_calling_llms
        yield from self._process_llm_stream(prompt=prompt, tools=None)
      File "/app/danswer/llm/answering/answer.py", line 331, in _process_llm_stream
        for message in self.llm.stream(
      File "/app/danswer/llm/chat_llm.py", line 366, in _stream_implementation
        for part in response:
      File "/usr/local/lib/python3.11/site-packages/litellm/utils.py", line 8242, in __next__
        raise exception_type(
              ^^^^^^^^^^^^^^^
      File "/usr/local/lib/python3.11/site-packages/litellm/litellm_core_utils/exception_mapping_utils.py", line 2033, in exception_type
        raise e
      File "/usr/local/lib/python3.11/site-packages/litellm/litellm_core_utils/exception_mapping_utils.py", line 515, in exception_type
        raise litellm.InternalServerError(
    litellm.exceptions.InternalServerError: litellm.InternalServerError: AnthropicException - Overloaded. Handle with `litellm.InternalServerError`.

**Comment by johnfelipe** [comment]
Give me best option for model and for search.
