### ISSUE TITLE
Loopio Integration Errors Out  `Document id Input should be a valid string`

### ISSUE THREAD

**Issue by ahmadassaf** [danswer-ai/danswer#2758]
Loopio integration currently fails with the following:

```
Traceback (most recent call last):
  File "/app/danswer/background/indexing/run_indexing.py", line 195, in _run_indexing
    for doc_batch in connector_runner.run():
  File "/app/danswer/connectors/connector_runner.py", line 48, in run
    yield from self.doc_batch_generator
  File "/app/danswer/connectors/loopio/connector.py", line 163, in _process_entries
    Document(
  File "/usr/local/lib/python3.11/site-packages/pydantic/main.py", line 193, in __init__
    self.__pydantic_validator__.validate_python(data, self_instance=self)
pydantic_core._pydantic_core.ValidationError: 1 validation error for Document
id
  Input should be a valid string [type=string_type, input_value=2398237, input_type=int]
    For further information visit https://errors.pydantic.dev/2.8/v/string_type
```

**Comment by rkuo-danswer** [comment]
This looks like a simple type conversion error so I'm putting in a one liner fix. Let us know if this doesn't solve your issue.

https://github.com/danswer-ai/danswer/pull/2909
