### ISSUE TITLE
api_server can not start 

### ISSUE THREAD

**Issue by maozhanlei** [danswer-ai/danswer#290]
ValueError: invalid literal for int() with base 10: ''
Traceback (most recent call last):
  File "/usr/local/bin/alembic", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/local/lib/python3.11/site-packages/alembic/config.py", line 591, in main
    CommandLine(prog=prog).main(argv=argv)
  File "/usr/local/lib/python3.11/site-packages/alembic/config.py", line 585, in main
    self.run_cmd(cfg, options)
  File "/usr/local/lib/python3.11/site-packages/alembic/config.py", line 562, in run_cmd
    fn(
  File "/usr/local/lib/python3.11/site-packages/alembic/command.py", line 378, in upgrade
    script.run_env()
  File "/usr/local/lib/python3.11/site-packages/alembic/script/base.py", line 576, in run_env
    util.load_python_file(self.dir, "env.py")
  File "/usr/local/lib/python3.11/site-packages/alembic/util/pyfiles.py", line 94, in load_python_file
    module = load_module_py(module_id, path)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/alembic/util/pyfiles.py", line 110, in load_module_py
    spec.loader.exec_module(module)  # type: ignore
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/app/alembic/env.py", line 5, in <module>
    from danswer.db.engine import build_connection_string
  File "/app/danswer/db/engine.py", line 14, in <module>
    from danswer.configs.app_configs import POSTGRES_DB
  File "/app/danswer/configs/app_configs.py", line 118, in <module>
    QA_TIMEOUT = int(os.environ.get("QA_TIMEOUT", "10"))  # 10 seconds

**Comment by yuhongsun96** [comment]
Hi, slight bug that crept into the codebase, was fixed shortly after this ticket, could you try again?

**Comment by yuhongsun96** [comment]
Sorry for the slow response, we're generally more active on slack: https://join.slack.com/t/danswer/shared_invite/zt-1u3h3ke3b-VGh1idW19R8oiNRiKBYv2w
