### ISSUE TITLE
Confluence error - latest version of danswer

### ISSUE THREAD

**Issue by johnfelipe** [danswer-ai/danswer#3117]
Traceback (most recent call last):
      File "/app/danswer/background/indexing/run_indexing.py", line 273, in _run_indexing
        new_docs, total_batch_chunks = indexing_pipeline(
                                       ^^^^^^^^^^^^^^^^^^
      File "/app/danswer/indexing/indexing_pipeline.py", line 144, in index_doc_batch_with_handler
        r = index_doc_batch(
            ^^^^^^^^^^^^^^^^
      File "/app/danswer/utils/timing.py", line 31, in wrapped_func
        result = func(*args, **kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^
      File "/app/danswer/indexing/indexing_pipeline.py", line 343, in index_doc_batch
        insertion_records = document_index.index(chunks=access_aware_chunks)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/app/danswer/document_index/vespa/index.py", line 347, in index
        batch_index_vespa_chunks(
      File "/app/danswer/document_index/vespa/indexing_utils.py", line 222, in batch_index_vespa_chunks
        future.result()
      File "/usr/local/lib/python3.11/concurrent/futures/_base.py", line 449, in result
        return self.__get_result()
               ^^^^^^^^^^^^^^^^^^^
      File "/usr/local/lib/python3.11/concurrent/futures/_base.py", line 401, in __get_result
        raise self._exception
      File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
        result = self.fn(*self.args, **self.kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/usr/local/lib/python3.11/site-packages/decorator.py", line 232, in fun
        return caller(func, *(extras + args), **kw)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/usr/local/lib/python3.11/site-packages/retry/api.py", line 73, in retry_decorator
        return __retry_internal(partial(f, *args, **kwargs), exceptions, tries, delay, max_delay, backoff, jitter,
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/usr/local/lib/python3.11/site-packages/retry/api.py", line 33, in __retry_internal
        return f()
               ^^^
      File "/app/danswer/document_index/vespa/indexing_utils.py", line 197, in _index_vespa_chunk
        raise e
      File "/app/danswer/document_index/vespa/indexing_utils.py", line 192, in _index_vespa_chunk
        res.raise_for_status()
      File "/usr/local/lib/python3.11/site-packages/httpx/_models.py", line 761, in raise_for_status
        raise HTTPStatusError(message, request=request, response=self)
    httpx.HTTPStatusError: Server error '507 Insufficient Storage' for url 'http://index:8081/document/v1/default/danswer_chunk_nomic_ai_nomic_embed_text_v1/docid/ed32e999-9e4b-559c-8469-a996a68d6b57'
    For more information check: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/507

![SNAG-0221](https://github.com/user-attachments/assets/79b2e719-8326-471b-904a-42b0f14c1b78)

how can solve this?

**Comment by emerzon** [comment]
This is an issue with your Vespa DB instance. You need to increase the Vespa DB capacity (memory or filesystem)

**Comment by rkuo-danswer** [comment]
Opening a PR to add some specific helpful hinting for 507 to indicate that increasing memory / disk for Vespa is the likely fix.
