### ISSUE TITLE
Bizarre Error When Attempting to Index Google Drive

### ISSUE THREAD

**Issue by joemccann** [danswer-ai/danswer#319]
I've successfully authenticated my Google Drive and have attempted to have Danswer index the entire drive but am getting this bizarre and unclear error.

```js
Error Message:
Invalid Elementary Object starting with b')' @20677: b'\n1 0 0 1 4.22 5 Tm\n )Tj\n/Xi1 1 Tf\n3 Tr\n1 0 0 1 283.05 -10 Tm\n({[{JprBQvBuEHB_pns'
```

<img width="691" alt="CleanShot 2023-08-19 at 18 30 31" src="https://github.com/danswer-ai/danswer/assets/48234/5687e593-edf1-4eb5-a16e-472e84f3d45b">

**Comment by joemccann** [comment]
I checked the logs of the `danswer-stack-background-1` service and it appears it's an issue with `PyPDF2`:

```sh

2023-08-19 18:30:07 08/20/2023 01:30:06 AM         connector.py 219 : Parseable Documents in batch: ['.JPM_The J.P. Morgan View Equity multiples appear too high, with DM rate cuts remaining elusive_20230731.pdf.wXxoY7', 'Tech Sync - 2023', 'NAV Discussion', 'Live Options Data', 'Product Sync 2023', 'Jenni Bui Separation Agreement, August 4, 2023', 'Citi_US Economics NFP Preview – Labor market heating up in July_20230801.pdf', 'Citi_US Economics ISM Manufacturing edges up but still in contraction_20230801.pdf', 'Exxon Mobil Corp. (XOM) Updating estimates See near term upside to consensus from Refining and Permian_Guyana volumes .pdf', 'Global Markets Comment Market Stress Monitor - 1st August 2023.pdf', 'JPM_JPM_US_Market_Intell_2023-08-01_4476814(1).pdf', 'JPM AAPL - Establishing a Dec 2024 price target of $235 vs Dec 2023 price target of $190.pdf', 'Midday Market Intelligence pause(1).pdf', 'USA ISM Manufacturing Increases Less than Expected.pdf', 'JPM - Global commodity open interest value recovers to a 13-month high.pdf', 'South Korea Headline Inflation Drops to 2.3, as Expected.pdf']
2023-08-19 18:30:08 08/20/2023 01:30:07 AM            update.py 248 : Indexing job with id 11 failed due to Invalid Elementary Object starting with b')' @20677: b'\n1 0 0 1 4.22 5 Tm\n )Tj\n/Xi1 1 Tf\n3 Tr\n1 0 0 1 283.05 -10 Tm\n({[{JprBQvBuEHB_pns'
2023-08-19 18:30:08 Traceback (most recent call last):
2023-08-19 18:30:08   File "/app/danswer/background/update.py", line 199, in run_indexing_jobs
2023-08-19 18:30:08     for doc_batch in doc_batch_generator:
2023-08-19 18:30:08   File "/app/danswer/connectors/google_drive/connector.py", line 417, in poll_source
2023-08-19 18:30:08     yield from self._fetch_docs_from_drive(
2023-08-19 18:30:08   File "/app/danswer/connectors/google_drive/connector.py", line 399, in _fetch_docs_from_drive
2023-08-19 18:30:08     raise e
2023-08-19 18:30:08   File "/app/danswer/connectors/google_drive/connector.py", line 383, in _fetch_docs_from_drive
2023-08-19 18:30:08     text_contents = extract_text(file, service)
2023-08-19 18:30:08                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-08-19 18:30:08   File "/app/danswer/connectors/google_drive/connector.py", line 285, in extract_text
2023-08-19 18:30:08     return "\n".join(page.extract_text() for page in pdf_reader.pages)
2023-08-19 18:30:08            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-08-19 18:30:08   File "/app/danswer/connectors/google_drive/connector.py", line 285, in <genexpr>
2023-08-19 18:30:08     return "\n".join(page.extract_text() for page in pdf_reader.pages)
2023-08-19 18:30:08                      ^^^^^^^^^^^^^^^^^^^
2023-08-19 18:30:08   File "/usr/local/lib/python3.11/site-packages/PyPDF2/_page.py", line 1851, in extract_text
2023-08-19 18:30:08     return self._extract_text(
2023-08-19 18:30:08            ^^^^^^^^^^^^^^^^^^^
2023-08-19 18:30:08   File "/usr/local/lib/python3.11/site-packages/PyPDF2/_page.py", line 1356, in _extract_text
2023-08-19 18:30:08     content = ContentStream(content, pdf, "bytes")
2023-08-19 18:30:08               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-08-19 18:30:08   File "/usr/local/lib/python3.11/site-packages/PyPDF2/generic/_data_structures.py", line 877, in __init__
2023-08-19 18:30:08     self.__parse_content_stream(stream_bytes)
2023-08-19 18:30:08   File "/usr/local/lib/python3.11/site-packages/PyPDF2/generic/_data_structures.py", line 943, in __parse_content_stream
2023-08-19 18:30:08     operands.append(read_object(stream, None, self.forced_encoding))
2023-08-19 18:30:08                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-08-19 18:30:08   File "/usr/local/lib/python3.11/site-packages/PyPDF2/generic/_data_structures.py", line 1080, in read_object
2023-08-19 18:30:08     raise PdfReadError(
2023-08-19 18:30:08 PyPDF2.errors.PdfReadError: Invalid Elementary Object starting with b')' @20677: b'\n1 0 0 1 4.22 5 Tm\n )Tj\n/Xi1 1 Tf\n3 Tr\n1 0 0 1 283.05 -10 Tm\n({[{JprBQvBuEHB_pns'
```

**Comment by joemccann** [comment]
ChatGPT's suggestion:

The error trace you provided indicates that the error occurs when trying to extract text from a PDF document using the `PyPDF2` library. The specific error raised is `PyPDF2.errors.PdfReadError`, which points to an issue with reading the content of the PDF file.

Here's a breakdown of the error:

1. The function `extract_text(file, service)` in `connector.py` is attempting to extract text from a PDF document.
2. Inside this function, there's a generator expression that iterates over `pdf_reader.pages` and tries to extract text from each page using the `page.extract_text()` method.
3. This leads to the internal workings of the `PyPDF2` library, where the error is eventually raised in the `read_object` function.

To fix the issue:

1. **Handle the Exception**: One way to deal with this is to handle the exception where it's raised, allowing the application to continue processing other documents or pages even if one page or document fails. This can be done using a try-except block.

2. **Switch to Another Library**: `PyPDF2` is known to have some issues with certain types of PDFs. Consider switching to another library like `pdfminer.six` or `PyMuPDF` which might handle the extraction more gracefully.

3. **Check the PDF Document**: The error message indicates an issue with a specific byte sequence in the PDF content. It's possible that the PDF document is corrupted or not formatted correctly. You can try opening the PDF in a viewer to check if it displays correctly. If it's corrupted, you may need to obtain a new copy or skip processing this document.

Here's a potential modification to your code (option 1: handling the exception):

```python
def extract_text(file, service):
    try:
        return "\n".join(page.extract_text() for page in pdf_reader.pages)
    except PyPDF2.errors.PdfReadError as e:
        # Log the error for further inspection
        logging.error(f"Error extracting text from PDF: {e}")
        return ""
```

By implementing this, the program will log the error and return an empty string for problematic PDFs, allowing the rest of the processing to continue. You can then investigate the problematic PDFs separately.

**Comment by Weves** [comment]
Hey @joemccann, thanks for bringing up this issue. This is a weird one. If you're willing to test out different PDF parsing libraries, we're open to switching if another one works better.

I'll also add as a workaround we do have this `CONTINUE_ON_CONNECTOR_FAILURE` env variable. If this is set to `true`, then we will basically do the same as your above code snippet and continue despite running into parsing errors. When you get a chance, can you try this and let me know if it works for you?

**Comment by Zhangtiande** [comment]
You can create a separate script to test your pdf file, using pypdf library instead of PyPdf2; in the parsing of Chinese, the current PyPdf2 produces a lot of garbage, however, pypdf produces a lot less garbage.
In view of this, you can use the new script to try a different pdf parsing libraries

**Comment by joemccann** [comment]
I have thousands of PDF documents that I'm attempting to index so without
the error outputting the actual file that is throwing the error it will be
very difficult for me to find it.

I think having a graceful way of not indexing a file that throws the error
is probably the best solution and then have the failed PDF filenames output
either in the logs or to the end user in the UI would be very very helpful.

**Comment by yuhongsun96** [comment]
Hey @joemccann, your snippet looks good, do you want to create a PR and we can give you credit for the fix? :smile:

**Comment by joemccann** [comment]
Sorry was out on vacation. I'll do some digging but I'm not super clear
where in the codebase the change needs to go.

**Comment by yuhongsun96** [comment]
Similar/equivalent changes has been put in, closing this issue
