### ISSUE TITLE
Exception: Unable to instantiate TypesenseClient

### ISSUE THREAD

**Issue by jayo2005** [danswer-ai/danswer#342]
I cannot get the docker to run I have these following error on the danswer-stack-api_server-1

```
Starting Danswer Api Server
2023-08-27 15:13:17.298060: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-08-27 15:13:18.071564: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
08/27/2023 03:13:19 PM         gpt_4_all.py  38 : GPT4All library not installed. If you wish to run GPT4ALL (in memory) to power Danswer's Generative AI features, please install gpt4all==1.0.5. As of Aug 2023, this library is not compatible with M1 Mac.
INFO:     Started server process [10]
INFO:     Waiting for application startup.
08/27/2023 03:13:19 PM              main.py 156 : Using Internal Model: openai-chat-completion
08/27/2023 03:13:19 PM              main.py 157 : Actual LLM model version: gpt-3.5-turbo
08/27/2023 03:13:19 PM              main.py 162 : User Authentication is turned off
08/27/2023 03:13:19 PM              main.py 179 : Warming up local NLP models.
All model checkpoint layers were used when initializing TFDistilBertForSequenceClassification.
All the layers of TFDistilBertForSequenceClassification were initialized from the model checkpoint at danswer/intent-model.
If your task is similar to the task the model of the checkpoint was trained on, you can already use TFDistilBertForSequenceClassification for predictions without further training.
08/27/2023 03:13:22 PM              main.py 184 : Verifying query preprocessing (NLTK) data is downloaded
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
08/27/2023 03:13:23 PM              main.py 189 : Verifying public credential exists.
08/27/2023 03:13:23 PM              main.py 192 : Verifying Document Index(s) is/are available.
ERROR:    Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 677, in lifespan
    async with self.lifespan_context(app) as maybe_state:
  File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 566, in __aenter__
    await self._router.startup()
  File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 656, in startup
    handler()
  File "/app/danswer/main.py", line 193, in startup_event
    get_default_document_index().ensure_indices_exist()
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/danswer/datastores/document_index.py", line 109, in get_default_document_index
    return SplitDocumentIndex(index_name=collection)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/danswer/datastores/document_index.py", line 37, in __init__
    self.keyword_index = keyword_index_cls(index_name)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/danswer/datastores/typesense/store.py", line 255, in __init__
    self.ts_client = get_typesense_client()
                     ^^^^^^^^^^^^^^^^^^^^^^
  File "/app/danswer/utils/clients.py", line 47, in get_typesense_client
    raise Exception("Unable to instantiate TypesenseClient")
Exception: Unable to instantiate TypesenseClient
ERROR:    Application startup failed. Exiting.
```

**Comment by yuhongsun96** [comment]
Hey, we didn't get around to building/tagging the image yesterday, please try now!

We've moved to Vespa from Typesense/Qdrant
