### ISSUE TITLE
Expecting ',' delimiter: line 1 column 2154 (char 2153)

### ISSUE THREAD

**Issue by voatsap** [danswer-ai/danswer#460]
Got an exception each time I'm searching with AI:

`"Expecting ',' delimiter: line 1 column 2154 (char 2153)"
`
Using web connector and ChatGPT.
It starts providing me with the answer but then fails with this kind of exception.

<img width="659" alt="image" src="https://github.com/danswer-ai/danswer/assets/5065994/bdcead95-4ff3-4b4d-9d29-5709a08fe9f7">

Here the logs from API server:

```
09/19/2023 12:51:06 PM          qa_utils.py  91 : Model did not output in json format as expected.
09/19/2023 12:51:06 PM    search_backend.py 277 : Failed to run QA
Traceback (most recent call last):
  File "/app/danswer/server/search_backend.py", line 262, in stream_qa_portions
    for response_packet in qa_model.answer_question_stream(
  File "/app/danswer/direct_qa/qa_block.py", line 263, in answer_question_stream
    yield from self._qa_handler.process_llm_token_stream(
  File "/app/danswer/direct_qa/qa_block.py", line 65, in process_llm_token_stream
    yield from process_model_tokens(
  File "/app/danswer/direct_qa/qa_utils.py", line 269, in process_model_tokens
    yield extract_quotes_from_completed_token_stream(model_output, context_docs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/danswer/direct_qa/qa_utils.py", line 195, in extract_quotes_from_completed_token_stream
    answer, quotes = process_answer(model_output, context_chunks)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/danswer/direct_qa/qa_utils.py", line 162, in process_answer
    answer, quote_strings = separate_answer_quotes(answer_clean, is_json_prompt)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/danswer/direct_qa/qa_utils.py", line 87, in separate_answer_quotes
    model_raw_json = json.loads(answer_raw)
                     ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
               ^^^^^^^^^^^^^^^^^^^^^^
json.decoder.JSONDecodeError: Expecting ',' delimiter: line 1 column 2154 (char 2153)
09/19/2023 12:51:06 PM            timing.py  60 : stream_qa_portions took 24.84137773513794 seconds
```

    Image ID:      docker.io/danswer/danswer-backend@sha256:583b83cc8927bba568910d3214b66a2a26e356a1f9de3e31f14d04f8952f59db

**Comment by yuhongsun96** [comment]
A few things updated about this one
- now using strict=False which helps in some cases
- less ugly error reporting if the LLM fails to output in the expected format
- if the LLM output fails to parse as json, we try heuristically extracting what we need as a backup

**Comment by yuhongsun96** [comment]
Thanks for pointing this out!

Closing as the LLM can always fail to produce the relevant information, best we can do is try to minimize that and make it less disruptive to the user flow should it happen.
