### ISSUE TITLE
Client-Side Exception on Accessing Connector Details

### ISSUE THREAD

**Issue by alex-feel** [danswer-ai/danswer#700]
I've come across a client-side exception when trying to access the connector details page at [http://localhost:3000/admin/connectors/zulip](http://localhost:3000/admin/connectors/zulip).

The error message displayed is `Application error: a client-side exception has occurred (see the browser console for more information).`

Here's the console log snippet indicating a TypeError:

```js
2472-102c37ffe9670a49.js:1 TypeError: Cannot read properties of undefined (reading 'id')
    at MainSection (page-8e5f27bd9205a939.js:1:3441)
    at Mf (fd9d1056-36dcd17be5e66091.js:9:39686)
    at Bh (fd9d1056-36dcd17be5e66091.js:9:59173)
    at rC (fd9d1056-36dcd17be5e66091.js:9:113120)
    at Jk (fd9d1056-36dcd17be5e66091.js:9:102245)
    at Ik (fd9d1056-36dcd17be5e66091.js:9:101422)
    at df (fd9d1056-36dcd17be5e66091.js:9:101240)
    at ef (fd9d1056-36dcd17be5e66091.js:9:98669)
    at bf (fd9d1056-36dcd17be5e66091.js:9:37059)
    at af (fd9d1056-36dcd17be5e66091.js:9:37705)
window.console.error @ 2472-102c37ffe9670a49.js:1
gh @ fd9d1056-36dcd17be5e66091.js:9
i.callback @ fd9d1056-36dcd17be5e66091.js:9
fe @ fd9d1056-36dcd17be5e66091.js:9
ge @ fd9d1056-36dcd17be5e66091.js:9
gj @ fd9d1056-36dcd17be5e66091.js:9
ij @ fd9d1056-36dcd17be5e66091.js:9
jj @ fd9d1056-36dcd17be5e66091.js:9
ij @ fd9d1056-36dcd17be5e66091.js:9
jj @ fd9d1056-36dcd17be5e66091.js:9
ij @ fd9d1056-36dcd17be5e66091.js:9
jj @ fd9d1056-36dcd17be5e66091.js:9
ij @ fd9d1056-36dcd17be5e66091.js:9
jj @ fd9d1056-36dcd17be5e66091.js:9
ij @ fd9d1056-36dcd17be5e66091.js:9
jj @ fd9d1056-36dcd17be5e66091.js:9
ij @ fd9d1056-36dcd17be5e66091.js:9
jj @ fd9d1056-36dcd17be5e66091.js:9
ij @ fd9d1056-36dcd17be5e66091.js:9
jj @ fd9d1056-36dcd17be5e66091.js:9
ij @ fd9d1056-36dcd17be5e66091.js:9
jj @ fd9d1056-36dcd17be5e66091.js:9
ij @ fd9d1056-36dcd17be5e66091.js:9
Ok @ fd9d1056-36dcd17be5e66091.js:9
jf @ fd9d1056-36dcd17be5e66091.js:9
bf @ fd9d1056-36dcd17be5e66091.js:9
af @ fd9d1056-36dcd17be5e66091.js:9
(anonymous) @ fd9d1056-36dcd17be5e66091.js:9
```

This issue seems to be related to an undefined property access, potentially within the MainSection component. It would be great to have this investigated and resolved for continuity in managing connectors.

**Comment by yuhongsun96** [comment]
The connector pages have been reworked since then, I just tested Zulip, it seems ok. If you're still facing issues on the latest version, feel free to reopen.

Thanks, we appreciate you pointing out the issue!
