### ISSUE TITLE
Failed to prepare Vespa Danswer Index.

### ISSUE THREAD

**Issue by michaelfeil** [danswer-ai/danswer#711]
```
git checkout v0.2.64
```

```
docker compose -f docker-compose.dev.yml -p danswer-stack up --pull always --force-recreate
```

```
danswer-stack-api_server-1     | All model checkpoint layers were used when initializing TFDistilBertForSequenceClassification.
danswer-stack-api_server-1     | 
danswer-stack-api_server-1     | All the layers of TFDistilBertForSequenceClassification were initialized from the model checkpoint at danswer/intent-model.
danswer-stack-api_server-1     | If your task is similar to the task the model of the checkpoint was trained on, you can already use TFDistilBertForSequenceClassification for predictions without further training.
danswer-stack-api_server-1     | 11/09/2023 10:08:37 AM              main.py 201 : Verifying query preprocessing (NLTK) data is downloaded
danswer-stack-api_server-1     | 11/09/2023 10:08:37 AM              main.py 206 : Verifying public credential exists.
danswer-stack-api_server-1     | 11/09/2023 10:08:37 AM              main.py 209 : Loading default Chat Personas
danswer-stack-api_server-1     | 11/09/2023 10:08:37 AM              main.py 212 : Verifying Document Index(s) is/are available.
danswer-stack-api_server-1     | ERROR:    Traceback (most recent call last):
danswer-stack-api_server-1     |   File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 677, in lifespan
danswer-stack-api_server-1     |     async with self.lifespan_context(app) as maybe_state:
danswer-stack-api_server-1     |   File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 566, in __aenter__
danswer-stack-api_server-1     |     await self._router.startup()
danswer-stack-api_server-1     |   File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 656, in startup
danswer-stack-api_server-1     |     handler()
danswer-stack-api_server-1     |   File "/app/danswer/main.py", line 213, in startup_event
danswer-stack-api_server-1     |     get_default_document_index().ensure_indices_exist()
danswer-stack-api_server-1     |   File "/app/danswer/document_index/vespa/index.py", line 495, in ensure_indices_exist
danswer-stack-api_server-1     |     raise RuntimeError(
danswer-stack-api_server-1     | RuntimeError: Failed to prepare Vespa Danswer Index. Response: <html><head><title>502 Bad Gateway</title></head>
danswer-stack-api_server-1     | <body><h1>DNS error</h1>
danswer-stack-api_server-1     | <p>DNS error (the host name of the page you are looking for does not exist)<br><br>Please check that the host name has been spelled correctly.<br></p>
danswer-stack-api_server-1     | <!--Zscaler/6.2--></body></html>
danswer-stack-api_server-1     | 
danswer-stack-api_server-1     | 
danswer-stack-api_server-1     | ERROR:    Application startup failed. Exiting.
```

**Comment by Xi-Meng** [comment]
Excuse me，so may I ask how to solve this problem？ I am also coming across this problem

**Comment by yoogoc** [comment]
+1

**Comment by luqijun** [comment]
I sovled the problem by passing the proxies  parameter :
```python
response = requests.post(deploy_url, headers=headers, data=zip_file, proxies={"http": "", "https": ""})
```
after that, `response.status_code` is 200.
